import {
  CaptchaGuard,
  CreateStaffSessionUseCase,
  ForgotPasswordRequestUseCase,
  ForgotPasswordVerifyOtpUseCase,
  LoginHardeningService,
  LogoutUseCase,
  MfaRequestOtpUseCase,
  MfaVerifyUseCase,
  PasswordLoginUseCase,
  RefreshSessionUseCase,
  RecordLoginService,
  RequestOtpUseCase,
  ResetPasswordUseCase,
  SetInitialPasswordUseCase,
  ValidateMfaPendingTokenUseCase,
  ValidateVerifiedRegisterTokenUseCase,
  VerifyOtpUseCase,
} from '@hivork/application';
import {
  Argon2PasswordHasher,
  ConsoleSmsAdapter,
  JwtTokenService,
  NoopCaptchaVerifier,
  OtpRateLimiterService,
  PrismaAuditService,
  PrismaGlobalCustomerRepository,
  PrismaModule,
  PrismaStaffRepository,
  PrismaStaffSessionRepository,
  PrismaTenantRepository,
  PrismaTenantSettingsRepository,
  PrismaUserCredentialRepository,
  PrismaUserMfaPort,
  PrismaUserRepository,
  PrismaUserSessionRevocationService,
  UaParserDeviceLabelService,
  RedisForgotPasswordRateLimiter,
  RedisOtpStore,
  RedisPasswordLoginFailureCounter,
  RedisResetTokenConsumptionStore,
  RedisService,
  RedisStaffSessionRefreshBlacklistService,
  RedisTokenBlacklistService,
  RedisUserRefreshInvalidationService,
  SettingsSchemaRegistry,
  TurnstileCaptchaVerifier,
  LoginRateLimiterService,
  IpAllowlistService,
} from '@hivork/infrastructure';
import { Module } from '@nestjs/common';

import { AuthCommonModule } from '../common/auth-common.module';
import { MfaTotpInfrastructureModule } from '../core/mfa/mfa-totp-infrastructure.module';
import { StaffPasswordModule } from '../core/staff/staff-password.module';
import { AppConfigService } from '../config/app-config.service';
import { AuthController } from './auth.controller';

@Module({
  imports: [PrismaModule, AuthCommonModule, MfaTotpInfrastructureModule, StaffPasswordModule],
  controllers: [AuthController],
  providers: [
    ConsoleSmsAdapter,
    RedisOtpStore,
    RedisTokenBlacklistService,
    RedisForgotPasswordRateLimiter,
    RedisResetTokenConsumptionStore,
    RedisUserRefreshInvalidationService,
    PrismaUserSessionRevocationService,
    RedisStaffSessionRefreshBlacklistService,
    PrismaGlobalCustomerRepository,
    PrismaUserRepository,
    PrismaUserCredentialRepository,
    PrismaTenantRepository,
    Argon2PasswordHasher,
    RedisPasswordLoginFailureCounter,
    LoginRateLimiterService,
    {
      provide: 'ICaptchaVerifier',
      useFactory: (config: AppConfigService) => {
        if (!config.captchaEnabled || config.captchaProvider === 'noop') {
          return new NoopCaptchaVerifier();
        }
        return new TurnstileCaptchaVerifier(config.captchaSecretKey);
      },
      inject: [AppConfigService],
    },
    {
      provide: CaptchaGuard,
      useFactory: (verifier: NoopCaptchaVerifier | TurnstileCaptchaVerifier, config: AppConfigService) =>
        new CaptchaGuard(verifier, {
          enabled: config.captchaEnabled,
          bypassToken: config.captchaBypassToken,
        }),
      inject: ['ICaptchaVerifier', AppConfigService],
    },
    {
      provide: IpAllowlistService,
      useFactory: (
        settingsRepository: PrismaTenantSettingsRepository,
        schemaRegistry: SettingsSchemaRegistry,
        audit: PrismaAuditService,
        config: AppConfigService,
      ) =>
        new IpAllowlistService(
          settingsRepository,
          schemaRegistry,
          audit,
          config.ipAllowlistBypassToken,
        ),
      inject: [
        PrismaTenantSettingsRepository,
        SettingsSchemaRegistry,
        PrismaAuditService,
        AppConfigService,
      ],
    },
    {
      provide: LoginHardeningService,
      useFactory: (
        captchaGuard: CaptchaGuard,
        failureCounter: RedisPasswordLoginFailureCounter,
        settingsRepository: PrismaTenantSettingsRepository,
        schemaRegistry: SettingsSchemaRegistry,
        ipAllowlist: IpAllowlistService,
      ) =>
        new LoginHardeningService(
          captchaGuard,
          failureCounter,
          settingsRepository,
          schemaRegistry,
          ipAllowlist,
        ),
      inject: [
        CaptchaGuard,
        RedisPasswordLoginFailureCounter,
        PrismaTenantSettingsRepository,
        SettingsSchemaRegistry,
        IpAllowlistService,
      ],
    },
    {
      provide: ValidateMfaPendingTokenUseCase,
      useFactory: (tokens: JwtTokenService, tokenBlacklist: RedisTokenBlacklistService) =>
        new ValidateMfaPendingTokenUseCase(tokens, tokenBlacklist),
      inject: [JwtTokenService, RedisTokenBlacklistService],
    },
    {
      provide: OtpRateLimiterService,
      useFactory: (redis: RedisService, config: AppConfigService) =>
        new OtpRateLimiterService(redis, config.otpRateLimitPerMinute),
      inject: [RedisService, AppConfigService],
    },
    {
      provide: ValidateVerifiedRegisterTokenUseCase,
      useFactory: (tokens: JwtTokenService, tokenBlacklist: RedisTokenBlacklistService) =>
        new ValidateVerifiedRegisterTokenUseCase(tokens, tokenBlacklist),
      inject: [JwtTokenService, RedisTokenBlacklistService],
    },
    {
      provide: SetInitialPasswordUseCase,
      useFactory: (
        validateVerifiedToken: ValidateVerifiedRegisterTokenUseCase,
        userRepository: PrismaUserRepository,
        credentialRepository: PrismaUserCredentialRepository,
        passwordHasher: Argon2PasswordHasher,
        audit: PrismaAuditService,
      ) =>
        new SetInitialPasswordUseCase(
          validateVerifiedToken,
          userRepository,
          credentialRepository,
          passwordHasher,
          audit,
        ),
      inject: [
        ValidateVerifiedRegisterTokenUseCase,
        PrismaUserRepository,
        PrismaUserCredentialRepository,
        Argon2PasswordHasher,
        PrismaAuditService,
      ],
    },
    PrismaUserRepository,
    PrismaStaffSessionRepository,
    PrismaTenantSettingsRepository,
    SettingsSchemaRegistry,
    UaParserDeviceLabelService,
    {
      provide: RecordLoginService,
      useFactory: (
        staffRepository: PrismaStaffRepository,
        userRepository: PrismaUserRepository,
        deviceLabels: UaParserDeviceLabelService,
        settingsRepository: PrismaTenantSettingsRepository,
        schemaRegistry: SettingsSchemaRegistry,
      ) =>
        new RecordLoginService(
          staffRepository,
          userRepository,
          deviceLabels,
          settingsRepository,
          schemaRegistry,
        ),
      inject: [
        PrismaStaffRepository,
        PrismaUserRepository,
        UaParserDeviceLabelService,
        PrismaTenantSettingsRepository,
        SettingsSchemaRegistry,
      ],
    },
    {
      provide: CreateStaffSessionUseCase,
      useFactory: (
        staffSessions: PrismaStaffSessionRepository,
        deviceLabels: UaParserDeviceLabelService,
      ) => new CreateStaffSessionUseCase(staffSessions, deviceLabels),
      inject: [PrismaStaffSessionRepository, UaParserDeviceLabelService],
    },
    {
      provide: PasswordLoginUseCase,
      useFactory: (
        userRepository: PrismaUserRepository,
        credentialRepository: PrismaUserCredentialRepository,
        passwordHasher: Argon2PasswordHasher,
        staffRepository: PrismaStaffRepository,
        tenantRepository: PrismaTenantRepository,
        tokens: JwtTokenService,
        userMfa: PrismaUserMfaPort,
        loginHardening: LoginHardeningService,
        loginRateLimiter: LoginRateLimiterService,
        settingsRepository: PrismaTenantSettingsRepository,
        schemaRegistry: SettingsSchemaRegistry,
        audit: PrismaAuditService,
        createStaffSession: CreateStaffSessionUseCase,
        recordLogin: RecordLoginService,
      ) =>
        new PasswordLoginUseCase(
          userRepository,
          credentialRepository,
          passwordHasher,
          staffRepository,
          tenantRepository,
          tokens,
          userMfa,
          loginHardening,
          loginRateLimiter,
          settingsRepository,
          schemaRegistry,
          audit,
          createStaffSession,
          recordLogin,
        ),
      inject: [
        PrismaUserRepository,
        PrismaUserCredentialRepository,
        Argon2PasswordHasher,
        PrismaStaffRepository,
        PrismaTenantRepository,
        JwtTokenService,
        PrismaUserMfaPort,
        LoginHardeningService,
        LoginRateLimiterService,
        PrismaTenantSettingsRepository,
        SettingsSchemaRegistry,
        PrismaAuditService,
        CreateStaffSessionUseCase,
        RecordLoginService,
      ],
    },
    {
      provide: MfaRequestOtpUseCase,
      useFactory: (
        validateMfaToken: ValidateMfaPendingTokenUseCase,
        userRepository: PrismaUserRepository,
        userMfa: PrismaUserMfaPort,
        otpStore: RedisOtpStore,
        rateLimiter: OtpRateLimiterService,
        sms: ConsoleSmsAdapter,
        config: AppConfigService,
      ) =>
        new MfaRequestOtpUseCase(
          validateMfaToken,
          userRepository,
          userMfa,
          otpStore,
          rateLimiter,
          sms,
          config.otpTtlSeconds,
        ),
      inject: [
        ValidateMfaPendingTokenUseCase,
        PrismaUserRepository,
        PrismaUserMfaPort,
        RedisOtpStore,
        OtpRateLimiterService,
        ConsoleSmsAdapter,
        AppConfigService,
      ],
    },
    {
      provide: MfaVerifyUseCase,
      useFactory: (
        validateMfaToken: ValidateMfaPendingTokenUseCase,
        userRepository: PrismaUserRepository,
        staffRepository: PrismaStaffRepository,
        userMfa: PrismaUserMfaPort,
        otpStore: RedisOtpStore,
        tokens: JwtTokenService,
        audit: PrismaAuditService,
        createStaffSession: CreateStaffSessionUseCase,
        recordLogin: RecordLoginService,
      ) =>
        new MfaVerifyUseCase(
          validateMfaToken,
          userRepository,
          staffRepository,
          userMfa,
          otpStore,
          tokens,
          audit,
          createStaffSession,
          recordLogin,
        ),
      inject: [
        ValidateMfaPendingTokenUseCase,
        PrismaUserRepository,
        PrismaStaffRepository,
        PrismaUserMfaPort,
        RedisOtpStore,
        JwtTokenService,
        PrismaAuditService,
        CreateStaffSessionUseCase,
        RecordLoginService,
      ],
    },
    {
      provide: RequestOtpUseCase,
      useFactory: (
        otpStore: RedisOtpStore,
        rateLimiter: OtpRateLimiterService,
        sms: ConsoleSmsAdapter,
        captchaGuard: CaptchaGuard,
        config: AppConfigService,
      ) => new RequestOtpUseCase(otpStore, rateLimiter, sms, captchaGuard, config.otpTtlSeconds),
      inject: [RedisOtpStore, OtpRateLimiterService, ConsoleSmsAdapter, CaptchaGuard, AppConfigService],
    },
    {
      provide: VerifyOtpUseCase,
      useFactory: (
        otpStore: RedisOtpStore,
        userRepository: PrismaUserRepository,
        staffRepository: PrismaStaffRepository,
        customerRepository: PrismaGlobalCustomerRepository,
        tenantRepository: PrismaTenantRepository,
        tokens: JwtTokenService,
        audit: PrismaAuditService,
        createStaffSession: CreateStaffSessionUseCase,
        recordLogin: RecordLoginService,
        loginHardening: LoginHardeningService,
      ) =>
        new VerifyOtpUseCase(
          otpStore,
          userRepository,
          staffRepository,
          customerRepository,
          tenantRepository,
          tokens,
          audit,
          createStaffSession,
          recordLogin,
          loginHardening,
        ),
      inject: [
        RedisOtpStore,
        PrismaUserRepository,
        PrismaStaffRepository,
        PrismaGlobalCustomerRepository,
        PrismaTenantRepository,
        JwtTokenService,
        PrismaAuditService,
        CreateStaffSessionUseCase,
        RecordLoginService,
        LoginHardeningService,
      ],
    },
    {
      provide: RefreshSessionUseCase,
      useFactory: (
        tokens: JwtTokenService,
        staffRepository: PrismaStaffRepository,
        customerRepository: PrismaGlobalCustomerRepository,
        tokenBlacklist: RedisTokenBlacklistService,
        refreshInvalidation: RedisUserRefreshInvalidationService,
        staffSessions: PrismaStaffSessionRepository,
        refreshBlacklist: RedisStaffSessionRefreshBlacklistService,
        audit: PrismaAuditService,
      ) =>
        new RefreshSessionUseCase(
          tokens,
          staffRepository,
          customerRepository,
          tokenBlacklist,
          refreshInvalidation,
          staffSessions,
          refreshBlacklist,
          audit,
        ),
      inject: [
        JwtTokenService,
        PrismaStaffRepository,
        PrismaGlobalCustomerRepository,
        RedisTokenBlacklistService,
        RedisUserRefreshInvalidationService,
        PrismaStaffSessionRepository,
        RedisStaffSessionRefreshBlacklistService,
        PrismaAuditService,
      ],
    },
    {
      provide: ForgotPasswordRequestUseCase,
      useFactory: (
        userRepository: PrismaUserRepository,
        credentialRepository: PrismaUserCredentialRepository,
        otpStore: RedisOtpStore,
        sms: ConsoleSmsAdapter,
        rateLimiter: RedisForgotPasswordRateLimiter,
        loginHardening: LoginHardeningService,
        audit: PrismaAuditService,
        config: AppConfigService,
      ) =>
        new ForgotPasswordRequestUseCase(
          userRepository,
          credentialRepository,
          otpStore,
          sms,
          rateLimiter,
          loginHardening,
          audit,
          config.otpTtlSeconds,
        ),
      inject: [
        PrismaUserRepository,
        PrismaUserCredentialRepository,
        RedisOtpStore,
        ConsoleSmsAdapter,
        RedisForgotPasswordRateLimiter,
        LoginHardeningService,
        PrismaAuditService,
        AppConfigService,
      ],
    },
    {
      provide: ForgotPasswordVerifyOtpUseCase,
      useFactory: (
        userRepository: PrismaUserRepository,
        credentialRepository: PrismaUserCredentialRepository,
        otpStore: RedisOtpStore,
        tokens: JwtTokenService,
        audit: PrismaAuditService,
      ) =>
        new ForgotPasswordVerifyOtpUseCase(
          userRepository,
          credentialRepository,
          otpStore,
          tokens,
          audit,
        ),
      inject: [
        PrismaUserRepository,
        PrismaUserCredentialRepository,
        RedisOtpStore,
        JwtTokenService,
        PrismaAuditService,
      ],
    },
    {
      provide: ResetPasswordUseCase,
      useFactory: (
        tokens: JwtTokenService,
        resetTokenConsumption: RedisResetTokenConsumptionStore,
        userRepository: PrismaUserRepository,
        credentialRepository: PrismaUserCredentialRepository,
        passwordHasher: Argon2PasswordHasher,
        sessionRevocation: PrismaUserSessionRevocationService,
        refreshInvalidation: RedisUserRefreshInvalidationService,
        rateLimiter: RedisForgotPasswordRateLimiter,
        audit: PrismaAuditService,
      ) =>
        new ResetPasswordUseCase(
          tokens,
          resetTokenConsumption,
          userRepository,
          credentialRepository,
          passwordHasher,
          sessionRevocation,
          refreshInvalidation,
          rateLimiter,
          audit,
        ),
      inject: [
        JwtTokenService,
        RedisResetTokenConsumptionStore,
        PrismaUserRepository,
        PrismaUserCredentialRepository,
        Argon2PasswordHasher,
        PrismaUserSessionRevocationService,
        RedisUserRefreshInvalidationService,
        RedisForgotPasswordRateLimiter,
        PrismaAuditService,
      ],
    },
    {
      provide: LogoutUseCase,
      useFactory: (
        tokens: JwtTokenService,
        tokenBlacklist: RedisTokenBlacklistService,
        staffSessions: PrismaStaffSessionRepository,
        refreshBlacklist: RedisStaffSessionRefreshBlacklistService,
        audit: PrismaAuditService,
      ) =>
        new LogoutUseCase(tokens, tokenBlacklist, staffSessions, refreshBlacklist, audit),
      inject: [
        JwtTokenService,
        RedisTokenBlacklistService,
        PrismaStaffSessionRepository,
        RedisStaffSessionRefreshBlacklistService,
        PrismaAuditService,
      ],
    },
  ],
})
export class AuthModule {}
