/** Check lifecycle domain error codes — IFP-112 / IFP-114 */
export const CheckDomainErrorCode = {
  CHECK_NOT_DUE: 'CHECK_NOT_DUE',
  CHECK_STATUS_INVALID: 'CHECK_STATUS_INVALID',
  CHECK_AMOUNT_INVALID: 'CHECK_AMOUNT_INVALID',
  CHECK_TYPE_NOT_RECEIVABLE: 'CHECK_TYPE_NOT_RECEIVABLE',
  CHECK_ALREADY_BOUNCED: 'CHECK_ALREADY_BOUNCED',
  CHECK_ALREADY_COLLECTED: 'CHECK_ALREADY_COLLECTED',
  CHECK_INVALID_STATE: 'CHECK_INVALID_STATE',
  BOUNCE_REASON_REQUIRED: 'BOUNCE_REASON_REQUIRED',
  TRANSFER_TARGET_REQUIRED: 'TRANSFER_TARGET_REQUIRED',
  PAYEE_NAME_REQUIRED: 'PAYEE_NAME_REQUIRED',
  FIELD_REQUIRED: 'FIELD_REQUIRED',
} as const;

export type CheckDomainErrorCode =
  (typeof CheckDomainErrorCode)[keyof typeof CheckDomainErrorCode];
