/** Payment ledger domain error codes — IFP-102 */
export const LedgerDomainErrorCode = {
  AMOUNT_INVALID: 'AMOUNT_INVALID',
  LEDGER_ALREADY_VOIDED: 'LEDGER_ALREADY_VOIDED',
  LEDGER_ENTRY_NOT_REFUNDABLE: 'LEDGER_ENTRY_NOT_REFUNDABLE',
  REVERSAL_AMOUNT_MISMATCH: 'REVERSAL_AMOUNT_MISMATCH',
  REVERSAL_DIRECTION_INVALID: 'REVERSAL_DIRECTION_INVALID',
  VOID_REASON_REQUIRED: 'VOID_REASON_REQUIRED',
  FIELD_REQUIRED: 'FIELD_REQUIRED',
  ENTRY_TYPE_DIRECTION_MISMATCH: 'ENTRY_TYPE_DIRECTION_MISMATCH',
} as const;

export type LedgerDomainErrorCode =
  (typeof LedgerDomainErrorCode)[keyof typeof LedgerDomainErrorCode];
