import {
  AUDIT_SERVICE,
  BulkTagCustomersUseCase,
  BulkUntagCustomersUseCase,
  CreateCustomerNoteUseCase,
  CreateTenantCustomerUseCase,
  CUSTOMER_IMPORT_IDEMPOTENCY_STORE,
  CUSTOMER_MERGE_IDEMPOTENCY_STORE,
  CUSTOMER_PDF_EXPORT_WRITER,
  CUSTOMER_XLSX_EXPORT_WRITER,
  DeleteCustomerDocumentUseCase,
  DeleteCustomerNoteUseCase,
  ExportService,
  ExportTenantCustomersUseCase,
  FILE_STORAGE_PORT,
  FILE_VIRUS_SCAN_PORT,
  GetCustomerDocumentDownloadUseCase,
  GetCustomerTimelineUseCase,
  ListCustomerPaymentsUseCase,
  ListCustomerContractsUseCase,
  MergeTenantCustomersUseCase,
  TransferCustomerOwnershipUseCase,
  AdjustCustomerScoreUseCase,
  BlacklistTenantCustomerUseCase,
  UnblacklistTenantCustomerUseCase,
  GetTenantCustomerUseCase,
  ImportCustomersExcelUseCase,
  ListCustomerDocumentsUseCase,
  ListCustomerNotesUseCase,
  ListDeletedTenantCustomersUseCase,
  ListTenantCustomersUseCase,
  PdfExportService,
  RestoreTenantCustomerUseCase,
  SoftDeleteTenantCustomerUseCase,
  ArchiveTenantCustomerUseCase,
  UnarchiveTenantCustomerUseCase,
  UNIT_OF_WORK,
  OUTBOX_PUBLISHER,
  UpdateCustomerNoteUseCase,
  UpdateTenantCustomerUseCase,
  UploadCustomerDocumentUseCase,
  type AuditService,
  type ICustomerImportIdempotencyStore,
  type ICustomerPdfExportWriter,
  type ICustomerXlsxExportWriter,
  type IFileStoragePort,
  type IFileVirusScanPort,
} from '@hivork/application';
import {
  CustomerPdfExportWriter,
  CustomerTimelineQuery,
  CustomerPaymentsQuery,
  CustomerContractsQuery,
  CustomerXlsxExportWriter,
  PrismaBranchReader,
  PrismaCustomerAddressRepository,
  PrismaCustomerCategoryReader,
  PrismaCustomerContactPhoneRepository,
  PrismaCustomerDocumentRepository,
  PrismaCustomerNoteRepository,
  PrismaCustomerEmergencyContactRepository,
  PrismaGlobalCustomerRepository,
  PrismaModule,
  PrismaSaleRepository,
  PrismaStaffRepository,
  PrismaTenantCustomerRepository,
  PrismaTenantPlanReader,
  PrismaTenantRepository,
  PrismaTenantSettingsRepository,
  PrismaUnitOfWork,
  PrismaUserRepository,
  PrismaTenantCustomerMergeRepository,
  PrismaOutboxPublisher,
  RedisCustomerImportIdempotencyStore,
  RedisCustomerMergeIdempotencyStore,
  RedisExportRateLimiterService,
  RedisModule,
} from '@hivork/infrastructure';
import { Module } from '@nestjs/common';

import { AuthCommonModule } from '../common/auth-common.module';
import { FilesModule } from '../files/files.module.js';
import { PrintSnapshotsModule } from '../core/print/print-snapshots.module';
import { CustomerDocumentsController } from './customer-documents.controller.js';
import { CustomerNotesController } from './customer-notes.controller.js';
import { CustomersController } from './customers.controller';

@Module({
  imports: [PrismaModule, AuthCommonModule, RedisModule, PrintSnapshotsModule, FilesModule],
  controllers: [CustomersController, CustomerDocumentsController, CustomerNotesController],
  providers: [
    PrismaTenantCustomerRepository,
    PrismaCustomerDocumentRepository,
    PrismaCustomerAddressRepository,
    PrismaCustomerEmergencyContactRepository,
    PrismaCustomerContactPhoneRepository,
    PrismaCustomerCategoryReader,
    PrismaStaffRepository,
    PrismaTenantRepository,
    PrismaGlobalCustomerRepository,
    PrismaUserRepository,
    PrismaBranchReader,
    PrismaTenantPlanReader,
    PrismaTenantSettingsRepository,
    PrismaSaleRepository,
    RedisCustomerImportIdempotencyStore,
    RedisCustomerMergeIdempotencyStore,
    PrismaTenantCustomerMergeRepository,
    PrismaOutboxPublisher,
    PrismaUnitOfWork,
    RedisExportRateLimiterService,
    ExportService,
    PdfExportService,
    CustomerXlsxExportWriter,
    CustomerPdfExportWriter,
    {
      provide: CUSTOMER_XLSX_EXPORT_WRITER,
      useExisting: CustomerXlsxExportWriter,
    },
    {
      provide: CUSTOMER_PDF_EXPORT_WRITER,
      useExisting: CustomerPdfExportWriter,
    },
    {
      provide: CUSTOMER_IMPORT_IDEMPOTENCY_STORE,
      useExisting: RedisCustomerImportIdempotencyStore,
    },
    {
      provide: CUSTOMER_MERGE_IDEMPOTENCY_STORE,
      useExisting: RedisCustomerMergeIdempotencyStore,
    },
    {
      provide: OUTBOX_PUBLISHER,
      useExisting: PrismaOutboxPublisher,
    },
    {
      provide: ListDeletedTenantCustomersUseCase,
      useFactory: (repository: PrismaTenantCustomerRepository) =>
        new ListDeletedTenantCustomersUseCase(repository),
      inject: [PrismaTenantCustomerRepository],
    },
    {
      provide: ListTenantCustomersUseCase,
      useFactory: (repository: PrismaTenantCustomerRepository) =>
        new ListTenantCustomersUseCase(repository),
      inject: [PrismaTenantCustomerRepository],
    },
    {
      provide: GetTenantCustomerUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
      ) => new GetTenantCustomerUseCase(tenantCustomers, sales),
      inject: [PrismaTenantCustomerRepository, PrismaSaleRepository],
    },
    {
      provide: MergeTenantCustomersUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        mergeRepository: PrismaTenantCustomerMergeRepository,
        unitOfWork: PrismaUnitOfWork,
        audit: AuditService,
        idempotency: RedisCustomerMergeIdempotencyStore,
        getTenantCustomer: GetTenantCustomerUseCase,
      ) =>
        new MergeTenantCustomersUseCase(
          tenantCustomers,
          sales,
          mergeRepository,
          unitOfWork,
          audit,
          idempotency,
          getTenantCustomer,
        ),
      inject: [
        PrismaTenantCustomerRepository,
        PrismaSaleRepository,
        PrismaTenantCustomerMergeRepository,
        PrismaUnitOfWork,
        AUDIT_SERVICE,
        CUSTOMER_MERGE_IDEMPOTENCY_STORE,
        GetTenantCustomerUseCase,
      ],
    },
    {
      provide: TransferCustomerOwnershipUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        staff: PrismaStaffRepository,
        unitOfWork: PrismaUnitOfWork,
        audit: AuditService,
        outbox: PrismaOutboxPublisher,
        getTenantCustomer: GetTenantCustomerUseCase,
      ) =>
        new TransferCustomerOwnershipUseCase(
          tenantCustomers,
          sales,
          staff,
          unitOfWork,
          audit,
          outbox,
          getTenantCustomer,
        ),
      inject: [
        PrismaTenantCustomerRepository,
        PrismaSaleRepository,
        PrismaStaffRepository,
        PrismaUnitOfWork,
        AUDIT_SERVICE,
        OUTBOX_PUBLISHER,
        GetTenantCustomerUseCase,
      ],
    },
    {
      provide: AdjustCustomerScoreUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        unitOfWork: PrismaUnitOfWork,
        audit: AuditService,
        getTenantCustomer: GetTenantCustomerUseCase,
      ) =>
        new AdjustCustomerScoreUseCase(
          tenantCustomers,
          sales,
          unitOfWork,
          audit,
          getTenantCustomer,
        ),
      inject: [
        PrismaTenantCustomerRepository,
        PrismaSaleRepository,
        PrismaUnitOfWork,
        AUDIT_SERVICE,
        GetTenantCustomerUseCase,
      ],
    },
    {
      provide: BlacklistTenantCustomerUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        unitOfWork: PrismaUnitOfWork,
        audit: AuditService,
        getTenantCustomer: GetTenantCustomerUseCase,
      ) =>
        new BlacklistTenantCustomerUseCase(
          tenantCustomers,
          sales,
          unitOfWork,
          audit,
          getTenantCustomer,
        ),
      inject: [
        PrismaTenantCustomerRepository,
        PrismaSaleRepository,
        PrismaUnitOfWork,
        AUDIT_SERVICE,
        GetTenantCustomerUseCase,
      ],
    },
    {
      provide: UnblacklistTenantCustomerUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        unitOfWork: PrismaUnitOfWork,
        audit: AuditService,
        getTenantCustomer: GetTenantCustomerUseCase,
      ) =>
        new UnblacklistTenantCustomerUseCase(
          tenantCustomers,
          sales,
          unitOfWork,
          audit,
          getTenantCustomer,
        ),
      inject: [
        PrismaTenantCustomerRepository,
        PrismaSaleRepository,
        PrismaUnitOfWork,
        AUDIT_SERVICE,
        GetTenantCustomerUseCase,
      ],
    },
    {
      provide: GetCustomerTimelineUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        timeline: CustomerTimelineQuery,
      ) => new GetCustomerTimelineUseCase(tenantCustomers, sales, timeline),
      inject: [PrismaTenantCustomerRepository, PrismaSaleRepository, CustomerTimelineQuery],
    },
    {
      provide: ListCustomerPaymentsUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        payments: CustomerPaymentsQuery,
      ) => new ListCustomerPaymentsUseCase(tenantCustomers, sales, payments),
      inject: [PrismaTenantCustomerRepository, PrismaSaleRepository, CustomerPaymentsQuery],
    },
    {
      provide: ListCustomerContractsUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        contracts: CustomerContractsQuery,
      ) => new ListCustomerContractsUseCase(tenantCustomers, sales, contracts),
      inject: [PrismaTenantCustomerRepository, PrismaSaleRepository, CustomerContractsQuery],
    },
    CustomerTimelineQuery,
    CustomerPaymentsQuery,
    CustomerContractsQuery,
    PrismaCustomerNoteRepository,
    {
      provide: UpdateTenantCustomerUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        globalCustomers: PrismaGlobalCustomerRepository,
        addresses: PrismaCustomerAddressRepository,
        emergencyContacts: PrismaCustomerEmergencyContactRepository,
        contactPhones: PrismaCustomerContactPhoneRepository,
        categories: PrismaCustomerCategoryReader,
        staff: PrismaStaffRepository,
        branches: PrismaBranchReader,
        sales: PrismaSaleRepository,
        unitOfWork: PrismaUnitOfWork,
        audit: AuditService,
      ) =>
        new UpdateTenantCustomerUseCase(
          tenantCustomers,
          globalCustomers,
          addresses,
          emergencyContacts,
          contactPhones,
          categories,
          staff,
          branches,
          sales,
          unitOfWork,
          audit,
        ),
      inject: [
        PrismaTenantCustomerRepository,
        PrismaGlobalCustomerRepository,
        PrismaCustomerAddressRepository,
        PrismaCustomerEmergencyContactRepository,
        PrismaCustomerContactPhoneRepository,
        PrismaCustomerCategoryReader,
        PrismaStaffRepository,
        PrismaBranchReader,
        PrismaSaleRepository,
        UNIT_OF_WORK,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: CreateCustomerNoteUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        notes: PrismaCustomerNoteRepository,
        audit: AuditService,
      ) => new CreateCustomerNoteUseCase(tenantCustomers, sales, notes, audit),
      inject: [
        PrismaTenantCustomerRepository,
        PrismaSaleRepository,
        PrismaCustomerNoteRepository,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: ListCustomerNotesUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        notes: PrismaCustomerNoteRepository,
      ) => new ListCustomerNotesUseCase(tenantCustomers, sales, notes),
      inject: [PrismaTenantCustomerRepository, PrismaSaleRepository, PrismaCustomerNoteRepository],
    },
    {
      provide: UpdateCustomerNoteUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        notes: PrismaCustomerNoteRepository,
        audit: AuditService,
      ) => new UpdateCustomerNoteUseCase(tenantCustomers, sales, notes, audit),
      inject: [
        PrismaTenantCustomerRepository,
        PrismaSaleRepository,
        PrismaCustomerNoteRepository,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: DeleteCustomerNoteUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        notes: PrismaCustomerNoteRepository,
        audit: AuditService,
      ) => new DeleteCustomerNoteUseCase(tenantCustomers, sales, notes, audit),
      inject: [
        PrismaTenantCustomerRepository,
        PrismaSaleRepository,
        PrismaCustomerNoteRepository,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: SoftDeleteTenantCustomerUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        settings: PrismaTenantSettingsRepository,
        unitOfWork: PrismaUnitOfWork,
        audit: AuditService,
      ) =>
        new SoftDeleteTenantCustomerUseCase(
          tenantCustomers,
          sales,
          settings,
          unitOfWork,
          audit,
        ),
      inject: [
        PrismaTenantCustomerRepository,
        PrismaSaleRepository,
        PrismaTenantSettingsRepository,
        UNIT_OF_WORK,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: RestoreTenantCustomerUseCase,
      useFactory: (tenantCustomers: PrismaTenantCustomerRepository, audit: AuditService) =>
        new RestoreTenantCustomerUseCase(tenantCustomers, audit),
      inject: [PrismaTenantCustomerRepository, AUDIT_SERVICE],
    },
    {
      provide: ArchiveTenantCustomerUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        audit: AuditService,
      ) => new ArchiveTenantCustomerUseCase(tenantCustomers, sales, audit),
      inject: [PrismaTenantCustomerRepository, PrismaSaleRepository, AUDIT_SERVICE],
    },
    {
      provide: UnarchiveTenantCustomerUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        audit: AuditService,
      ) => new UnarchiveTenantCustomerUseCase(tenantCustomers, sales, audit),
      inject: [PrismaTenantCustomerRepository, PrismaSaleRepository, AUDIT_SERVICE],
    },
    {
      provide: UNIT_OF_WORK,
      useClass: PrismaUnitOfWork,
    },
    {
      provide: CreateTenantCustomerUseCase,
      useFactory: (
        users: PrismaUserRepository,
        globalCustomers: PrismaGlobalCustomerRepository,
        tenantCustomers: PrismaTenantCustomerRepository,
        addresses: PrismaCustomerAddressRepository,
        emergencyContacts: PrismaCustomerEmergencyContactRepository,
        contactPhones: PrismaCustomerContactPhoneRepository,
        categories: PrismaCustomerCategoryReader,
        staff: PrismaStaffRepository,
        branches: PrismaBranchReader,
        tenantPlans: PrismaTenantPlanReader,
        unitOfWork: PrismaUnitOfWork,
        audit: AuditService,
      ) =>
        new CreateTenantCustomerUseCase(
          users,
          globalCustomers,
          tenantCustomers,
          addresses,
          emergencyContacts,
          contactPhones,
          categories,
          staff,
          branches,
          tenantPlans,
          unitOfWork,
          audit,
        ),
      inject: [
        PrismaUserRepository,
        PrismaGlobalCustomerRepository,
        PrismaTenantCustomerRepository,
        PrismaCustomerAddressRepository,
        PrismaCustomerEmergencyContactRepository,
        PrismaCustomerContactPhoneRepository,
        PrismaCustomerCategoryReader,
        PrismaStaffRepository,
        PrismaBranchReader,
        PrismaTenantPlanReader,
        UNIT_OF_WORK,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: ImportCustomersExcelUseCase,
      useFactory: (
        createTenantCustomer: CreateTenantCustomerUseCase,
        tenantCustomers: PrismaTenantCustomerRepository,
        tenantPlans: PrismaTenantPlanReader,
        categories: PrismaCustomerCategoryReader,
        idempotency: ICustomerImportIdempotencyStore,
        audit: AuditService,
      ) =>
        new ImportCustomersExcelUseCase(
          createTenantCustomer,
          tenantCustomers,
          tenantPlans,
          categories,
          idempotency,
          audit,
        ),
      inject: [
        CreateTenantCustomerUseCase,
        PrismaTenantCustomerRepository,
        PrismaTenantPlanReader,
        PrismaCustomerCategoryReader,
        CUSTOMER_IMPORT_IDEMPOTENCY_STORE,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: ExportTenantCustomersUseCase,
      useFactory: (
        repository: PrismaTenantCustomerRepository,
        tenants: PrismaTenantRepository,
        settings: PrismaTenantSettingsRepository,
        xlsxWriter: ICustomerXlsxExportWriter,
        pdfWriter: ICustomerPdfExportWriter,
        audit: AuditService,
        rateLimiter: RedisExportRateLimiterService,
      ) =>
        new ExportTenantCustomersUseCase(
          repository,
          tenants,
          settings,
          xlsxWriter,
          pdfWriter,
          audit,
          rateLimiter,
        ),
      inject: [
        PrismaTenantCustomerRepository,
        PrismaTenantRepository,
        PrismaTenantSettingsRepository,
        CUSTOMER_XLSX_EXPORT_WRITER,
        CUSTOMER_PDF_EXPORT_WRITER,
        AUDIT_SERVICE,
        RedisExportRateLimiterService,
      ],
    },
    {
      provide: BulkTagCustomersUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        audit: AuditService,
      ) => new BulkTagCustomersUseCase(tenantCustomers, sales, audit),
      inject: [PrismaTenantCustomerRepository, PrismaSaleRepository, AUDIT_SERVICE],
    },
    {
      provide: BulkUntagCustomersUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        audit: AuditService,
      ) => new BulkUntagCustomersUseCase(tenantCustomers, sales, audit),
      inject: [PrismaTenantCustomerRepository, PrismaSaleRepository, AUDIT_SERVICE],
    },
    {
      provide: UploadCustomerDocumentUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        documents: PrismaCustomerDocumentRepository,
        settings: PrismaTenantSettingsRepository,
        storage: IFileStoragePort,
        virusScan: IFileVirusScanPort,
        audit: AuditService,
      ) =>
        new UploadCustomerDocumentUseCase(
          tenantCustomers,
          sales,
          documents,
          settings,
          storage,
          virusScan,
          audit,
        ),
      inject: [
        PrismaTenantCustomerRepository,
        PrismaSaleRepository,
        PrismaCustomerDocumentRepository,
        PrismaTenantSettingsRepository,
        FILE_STORAGE_PORT,
        FILE_VIRUS_SCAN_PORT,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: ListCustomerDocumentsUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        documents: PrismaCustomerDocumentRepository,
      ) => new ListCustomerDocumentsUseCase(tenantCustomers, sales, documents),
      inject: [PrismaTenantCustomerRepository, PrismaSaleRepository, PrismaCustomerDocumentRepository],
    },
    {
      provide: DeleteCustomerDocumentUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        documents: PrismaCustomerDocumentRepository,
        audit: AuditService,
      ) => new DeleteCustomerDocumentUseCase(tenantCustomers, sales, documents, audit),
      inject: [
        PrismaTenantCustomerRepository,
        PrismaSaleRepository,
        PrismaCustomerDocumentRepository,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: GetCustomerDocumentDownloadUseCase,
      useFactory: (
        tenantCustomers: PrismaTenantCustomerRepository,
        sales: PrismaSaleRepository,
        documents: PrismaCustomerDocumentRepository,
        storage: IFileStoragePort,
      ) =>
        new GetCustomerDocumentDownloadUseCase(
          tenantCustomers,
          sales,
          documents,
          storage,
        ),
      inject: [
        PrismaTenantCustomerRepository,
        PrismaSaleRepository,
        PrismaCustomerDocumentRepository,
        FILE_STORAGE_PORT,
      ],
    },
  ],
})
export class CustomersModule {}
