import {
  AccelerateInstallmentUseCase,
  CloseSettlementBatchUseCase,
  CreateSettlementBatchUseCase,
  CreateUnifiedPaymentUseCase,
  DeferInstallmentUseCase,
  GeneratePaymentReceiptUseCase,
  GetReconciliationReportUseCase,
  GetSettlementBatchUseCase,
  InitOnlinePaymentUseCase,
  ListEnabledPaymentMethodsUseCase,
  ListInstallmentsUseCase,
  ListPaymentTransactionsUseCase,
  ListSettlementBatchesUseCase,
  ListChecksUseCase,
  MarkCheckBouncedUseCase,
  CollectCheckUseCase,
  TransferCheckUseCase,
  GetCheckTrackingUseCase,
  AddCheckTrackingNoteUseCase,
  UploadCheckImageUseCase,
  GetCheckImageUseCase,
  FILE_STORAGE_PORT,
  RegisterPayableCheckUseCase,
  RegisterReceivedCheckUseCase,
  RefundPaymentUseCase,
  ResolveDiscrepancyUseCase,
  RunReconciliationUseCase,
  VoidLedgerTransactionUseCase,
  PAYMENT_GATEWAY_REGISTRY,
  PDF_EXPORT_PORT,
  SendPaymentReceiptUseCase,
  WalletPaymentUseCase,
  type IPaymentGatewayRegistry,
  type IPdfExportPort,
  type IFileStoragePort,
  RecordCashManualPaymentUseCase,
  RecordBankTransferPaymentUseCase,
  RecordPosPaymentUseCase,
  RecordCheckPaymentUseCase,
  RecordFeePaymentUseCase,
  RescheduleInstallmentUseCase,
  ConfirmPaymentUseCase,
  RejectPaymentUseCase,
  VoidPaymentUseCase,
  WaiveInstallmentUseCase,
  ApplyPenaltyUseCase,
  CalculatePenaltyPreviewUseCase,
  ApplyDiscountUseCase,
  SplitInstallmentUseCase,
} from '@hivork/application';
import {
  MockPaymentGateway,
  MockPaymentGatewayRegistry,
  PrismaAuditService,
  PrismaBranchReader,
  PrismaInstallmentAdjustmentRepository,
  PrismaInstallmentOperationLogRepository,
  PrismaInstallmentRepository,
  PrismaModule,
  PrismaNotificationDispatcher,
  PrismaOutboxPublisher,
  PrismaPaymentAttemptRepository,
  PrismaPaymentLedgerRepository,
  PrismaSettlementBatchRepository,
  PrismaCheckRepository,
  PrismaStoredFileRepository,
  PrismaCheckTrackingNoteRepository,
  PrismaReconciliationRepository,
  PrismaPaymentReceiptRepository,
  PrismaSaleRepository,
  PrismaStaffRepository,
  PrismaTenantRepository,
  PrismaTenantSequenceRepository,
  PrismaTenantSettingsRepository,
  PrismaTenantPlanReader,
  PrismaUnitOfWork,
} from '@hivork/infrastructure';
import { Module } from '@nestjs/common';

import { FilesModule } from '../../files/files.module.js';
import { AuthCommonModule } from '../../common/auth-common.module.js';
import { PrintSnapshotsModule } from '../../core/print/print-snapshots.module.js';
import { AppConfigModule } from '../../config/app-config.module.js';
import { AppConfigService } from '../../config/app-config.service.js';
import { InstallmentAdjustmentsController } from './installment-adjustments.controller.js';
import { InstallmentOperationsController } from './installment-operations.controller.js';
import { InstallmentsController } from './installments.controller.js';
import { OnlinePaymentController } from './online-payment.controller.js';
import { PaymentConfirmationController } from './payment-confirmation.controller.js';
import { PaymentReceiptController } from './payment-receipt.controller.js';
import { PaymentRecordingController } from './payment-recording.controller.js';

import { PaymentTransactionsController } from '../payments/payment-transactions.controller.js';
import { ReconciliationController } from '../payments/reconciliation.controller.js';
import { SettlementController } from '../payments/settlement.controller.js';
import { ChecksController } from '../payments/checks.controller.js';
import { UnifiedPaymentsController } from '../payments/unified-payments.controller.js';

@Module({
  imports: [PrismaModule, AuthCommonModule, AppConfigModule, PrintSnapshotsModule, FilesModule],
  controllers: [
    InstallmentsController,
    InstallmentOperationsController,
    InstallmentAdjustmentsController,
    PaymentRecordingController,
    PaymentConfirmationController,
    PaymentReceiptController,
    PaymentTransactionsController,
    SettlementController,
    ChecksController,
    ReconciliationController,
    UnifiedPaymentsController,
    OnlinePaymentController,
  ],
  providers: [
    PrismaInstallmentRepository,
    PrismaInstallmentAdjustmentRepository,
    PrismaPaymentAttemptRepository,
    PrismaPaymentLedgerRepository,
    PrismaSettlementBatchRepository,
    PrismaCheckRepository,
    PrismaStoredFileRepository,
    PrismaCheckTrackingNoteRepository,
    PrismaReconciliationRepository,
    PrismaPaymentReceiptRepository,
    PrismaSaleRepository,
    PrismaStaffRepository,
    PrismaTenantRepository,
    PrismaTenantSequenceRepository,
    PrismaNotificationDispatcher,
    PrismaInstallmentOperationLogRepository,
    PrismaUnitOfWork,
    PrismaBranchReader,
    PrismaTenantSettingsRepository,
    PrismaTenantPlanReader,
    PrismaAuditService,
    PrismaOutboxPublisher,
    {
      provide: ListInstallmentsUseCase,
      useFactory: (installments: PrismaInstallmentRepository) =>
        new ListInstallmentsUseCase(installments),
      inject: [PrismaInstallmentRepository],
    },
    {
      provide: ListPaymentTransactionsUseCase,
      useFactory: (ledger: PrismaPaymentLedgerRepository) =>
        new ListPaymentTransactionsUseCase(ledger),
      inject: [PrismaPaymentLedgerRepository],
    },
    {
      provide: RefundPaymentUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        ledger: PrismaPaymentLedgerRepository,
        installments: PrismaInstallmentRepository,
        paymentAttempts: PrismaPaymentAttemptRepository,
        branches: PrismaBranchReader,
        gateways: IPaymentGatewayRegistry,
        audit: PrismaAuditService,
      ) =>
        new RefundPaymentUseCase(
          unitOfWork,
          ledger,
          installments,
          paymentAttempts,
          branches,
          gateways,
          audit,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaPaymentLedgerRepository,
        PrismaInstallmentRepository,
        PrismaPaymentAttemptRepository,
        PrismaBranchReader,
        PAYMENT_GATEWAY_REGISTRY,
        PrismaAuditService,
      ],
    },
    {
      provide: VoidLedgerTransactionUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        ledger: PrismaPaymentLedgerRepository,
        installments: PrismaInstallmentRepository,
        paymentAttempts: PrismaPaymentAttemptRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        audit: PrismaAuditService,
        outbox: PrismaOutboxPublisher,
      ) =>
        new VoidLedgerTransactionUseCase(
          unitOfWork,
          ledger,
          installments,
          paymentAttempts,
          branches,
          tenantSettings,
          audit,
          outbox,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaPaymentLedgerRepository,
        PrismaInstallmentRepository,
        PrismaPaymentAttemptRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PrismaAuditService,
        PrismaOutboxPublisher,
      ],
    },
    {
      provide: CreateSettlementBatchUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        settlements: PrismaSettlementBatchRepository,
        branches: PrismaBranchReader,
        sequences: PrismaTenantSequenceRepository,
        audit: PrismaAuditService,
      ) =>
        new CreateSettlementBatchUseCase(
          unitOfWork,
          settlements,
          branches,
          sequences,
          audit,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaSettlementBatchRepository,
        PrismaBranchReader,
        PrismaTenantSequenceRepository,
        PrismaAuditService,
      ],
    },
    {
      provide: CloseSettlementBatchUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        settlements: PrismaSettlementBatchRepository,
        paymentAttempts: PrismaPaymentAttemptRepository,
        audit: PrismaAuditService,
      ) =>
        new CloseSettlementBatchUseCase(
          unitOfWork,
          settlements,
          paymentAttempts,
          audit,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaSettlementBatchRepository,
        PrismaPaymentAttemptRepository,
        PrismaAuditService,
      ],
    },
    {
      provide: ListSettlementBatchesUseCase,
      useFactory: (settlements: PrismaSettlementBatchRepository) =>
        new ListSettlementBatchesUseCase(settlements),
      inject: [PrismaSettlementBatchRepository],
    },
    {
      provide: RegisterReceivedCheckUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        checks: PrismaCheckRepository,
        installments: PrismaInstallmentRepository,
        paymentAttempts: PrismaPaymentAttemptRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        audit: PrismaAuditService,
      ) =>
        new RegisterReceivedCheckUseCase(
          unitOfWork,
          checks,
          installments,
          paymentAttempts,
          branches,
          tenantSettings,
          audit,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaCheckRepository,
        PrismaInstallmentRepository,
        PrismaPaymentAttemptRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PrismaAuditService,
      ],
    },
    {
      provide: ListChecksUseCase,
      useFactory: (checks: PrismaCheckRepository) => new ListChecksUseCase(checks),
      inject: [PrismaCheckRepository],
    },
    {
      provide: RegisterPayableCheckUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        checks: PrismaCheckRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        audit: PrismaAuditService,
      ) =>
        new RegisterPayableCheckUseCase(
          unitOfWork,
          checks,
          branches,
          tenantSettings,
          audit,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaCheckRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PrismaAuditService,
      ],
    },
    {
      provide: MarkCheckBouncedUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        checks: PrismaCheckRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        audit: PrismaAuditService,
        outbox: PrismaOutboxPublisher,
      ) =>
        new MarkCheckBouncedUseCase(
          unitOfWork,
          checks,
          branches,
          tenantSettings,
          audit,
          outbox,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaCheckRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PrismaAuditService,
        PrismaOutboxPublisher,
      ],
    },
    {
      provide: CollectCheckUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        checks: PrismaCheckRepository,
        ledger: PrismaPaymentLedgerRepository,
        installments: PrismaInstallmentRepository,
        paymentAttempts: PrismaPaymentAttemptRepository,
        branches: PrismaBranchReader,
        audit: PrismaAuditService,
      ) =>
        new CollectCheckUseCase(
          unitOfWork,
          checks,
          ledger,
          installments,
          paymentAttempts,
          branches,
          audit,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaCheckRepository,
        PrismaPaymentLedgerRepository,
        PrismaInstallmentRepository,
        PrismaPaymentAttemptRepository,
        PrismaBranchReader,
        PrismaAuditService,
      ],
    },
    {
      provide: TransferCheckUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        checks: PrismaCheckRepository,
        branches: PrismaBranchReader,
        audit: PrismaAuditService,
      ) =>
        new TransferCheckUseCase(unitOfWork, checks, branches, audit),
      inject: [
        PrismaUnitOfWork,
        PrismaCheckRepository,
        PrismaBranchReader,
        PrismaAuditService,
      ],
    },
    {
      provide: GetCheckTrackingUseCase,
      useFactory: (
        checks: PrismaCheckRepository,
        trackingNotes: PrismaCheckTrackingNoteRepository,
        branches: PrismaBranchReader,
        audit: PrismaAuditService,
      ) => new GetCheckTrackingUseCase(checks, trackingNotes, branches, audit),
      inject: [
        PrismaCheckRepository,
        PrismaCheckTrackingNoteRepository,
        PrismaBranchReader,
        PrismaAuditService,
      ],
    },
    {
      provide: AddCheckTrackingNoteUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        checks: PrismaCheckRepository,
        trackingNotes: PrismaCheckTrackingNoteRepository,
        branches: PrismaBranchReader,
        audit: PrismaAuditService,
      ) =>
        new AddCheckTrackingNoteUseCase(
          unitOfWork,
          checks,
          trackingNotes,
          branches,
          audit,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaCheckRepository,
        PrismaCheckTrackingNoteRepository,
        PrismaBranchReader,
        PrismaAuditService,
      ],
    },
    {
      provide: UploadCheckImageUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        checks: PrismaCheckRepository,
        storedFiles: PrismaStoredFileRepository,
        storage: IFileStoragePort,
        branches: PrismaBranchReader,
        audit: PrismaAuditService,
      ) =>
        new UploadCheckImageUseCase(
          unitOfWork,
          checks,
          storedFiles,
          storage,
          branches,
          audit,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaCheckRepository,
        PrismaStoredFileRepository,
        FILE_STORAGE_PORT,
        PrismaBranchReader,
        PrismaAuditService,
      ],
    },
    {
      provide: GetCheckImageUseCase,
      useFactory: (
        checks: PrismaCheckRepository,
        storedFiles: PrismaStoredFileRepository,
        storage: IFileStoragePort,
        branches: PrismaBranchReader,
      ) => new GetCheckImageUseCase(checks, storedFiles, storage, branches),
      inject: [
        PrismaCheckRepository,
        PrismaStoredFileRepository,
        FILE_STORAGE_PORT,
        PrismaBranchReader,
      ],
    },
    {
      provide: GetSettlementBatchUseCase,
      useFactory: (settlements: PrismaSettlementBatchRepository) =>
        new GetSettlementBatchUseCase(settlements),
      inject: [PrismaSettlementBatchRepository],
    },
    {
      provide: RunReconciliationUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        settlements: PrismaSettlementBatchRepository,
        reconciliations: PrismaReconciliationRepository,
      ) => new RunReconciliationUseCase(unitOfWork, settlements, reconciliations),
      inject: [
        PrismaUnitOfWork,
        PrismaSettlementBatchRepository,
        PrismaReconciliationRepository,
      ],
    },
    {
      provide: GetReconciliationReportUseCase,
      useFactory: (
        reconciliations: PrismaReconciliationRepository,
        settlements: PrismaSettlementBatchRepository,
      ) => new GetReconciliationReportUseCase(reconciliations, settlements),
      inject: [PrismaReconciliationRepository, PrismaSettlementBatchRepository],
    },
    {
      provide: ResolveDiscrepancyUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        reconciliations: PrismaReconciliationRepository,
        settlements: PrismaSettlementBatchRepository,
        audit: PrismaAuditService,
      ) =>
        new ResolveDiscrepancyUseCase(
          unitOfWork,
          reconciliations,
          settlements,
          audit,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaReconciliationRepository,
        PrismaSettlementBatchRepository,
        PrismaAuditService,
      ],
    },
    {
      provide: ListEnabledPaymentMethodsUseCase,
      useFactory: (
        tenantSettings: PrismaTenantSettingsRepository,
        tenantPlans: PrismaTenantPlanReader,
      ) => new ListEnabledPaymentMethodsUseCase(tenantSettings, tenantPlans),
      inject: [PrismaTenantSettingsRepository, PrismaTenantPlanReader],
    },
    {
      provide: WalletPaymentUseCase,
      useFactory: () => new WalletPaymentUseCase(),
    },
    {
      provide: CreateUnifiedPaymentUseCase,
      useFactory: (
        tenantSettings: PrismaTenantSettingsRepository,
        tenantPlans: PrismaTenantPlanReader,
        paymentAttempts: PrismaPaymentAttemptRepository,
        recordCashManualPayment: RecordCashManualPaymentUseCase,
        recordBankTransferPayment: RecordBankTransferPaymentUseCase,
        recordPosPayment: RecordPosPaymentUseCase,
        recordCheckPayment: RecordCheckPaymentUseCase,
        initOnlinePayment: InitOnlinePaymentUseCase,
        walletPayment: WalletPaymentUseCase,
      ) =>
        new CreateUnifiedPaymentUseCase(
          tenantSettings,
          tenantPlans,
          paymentAttempts,
          recordCashManualPayment,
          recordBankTransferPayment,
          recordPosPayment,
          recordCheckPayment,
          initOnlinePayment,
          walletPayment,
        ),
      inject: [
        PrismaTenantSettingsRepository,
        PrismaTenantPlanReader,
        PrismaPaymentAttemptRepository,
        RecordCashManualPaymentUseCase,
        RecordBankTransferPaymentUseCase,
        RecordPosPaymentUseCase,
        RecordCheckPaymentUseCase,
        InitOnlinePaymentUseCase,
        WalletPaymentUseCase,
      ],
    },
    {
      provide: RescheduleInstallmentUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        installments: PrismaInstallmentRepository,
        operationLogs: PrismaInstallmentOperationLogRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        audit: PrismaAuditService,
      ) =>
        new RescheduleInstallmentUseCase(
          unitOfWork,
          installments,
          operationLogs,
          branches,
          tenantSettings,
          audit,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaInstallmentRepository,
        PrismaInstallmentOperationLogRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PrismaAuditService,
      ],
    },
    {
      provide: DeferInstallmentUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        installments: PrismaInstallmentRepository,
        operationLogs: PrismaInstallmentOperationLogRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        audit: PrismaAuditService,
      ) =>
        new DeferInstallmentUseCase(
          unitOfWork,
          installments,
          operationLogs,
          branches,
          tenantSettings,
          audit,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaInstallmentRepository,
        PrismaInstallmentOperationLogRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PrismaAuditService,
      ],
    },
    {
      provide: AccelerateInstallmentUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        installments: PrismaInstallmentRepository,
        operationLogs: PrismaInstallmentOperationLogRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        audit: PrismaAuditService,
      ) =>
        new AccelerateInstallmentUseCase(
          unitOfWork,
          installments,
          operationLogs,
          branches,
          tenantSettings,
          audit,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaInstallmentRepository,
        PrismaInstallmentOperationLogRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PrismaAuditService,
      ],
    },
    {
      provide: SplitInstallmentUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        installments: PrismaInstallmentRepository,
        operationLogs: PrismaInstallmentOperationLogRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        audit: PrismaAuditService,
      ) =>
        new SplitInstallmentUseCase(
          unitOfWork,
          installments,
          operationLogs,
          branches,
          tenantSettings,
          audit,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaInstallmentRepository,
        PrismaInstallmentOperationLogRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PrismaAuditService,
      ],
    },
    {
      provide: WaiveInstallmentUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        installments: PrismaInstallmentRepository,
        paymentAttempts: PrismaPaymentAttemptRepository,
        branches: PrismaBranchReader,
        audit: PrismaAuditService,
        outbox: PrismaOutboxPublisher,
      ) =>
        new WaiveInstallmentUseCase(
          unitOfWork,
          installments,
          paymentAttempts,
          branches,
          audit,
          outbox,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaInstallmentRepository,
        PrismaPaymentAttemptRepository,
        PrismaBranchReader,
        PrismaAuditService,
        PrismaOutboxPublisher,
      ],
    },
    {
      provide: CalculatePenaltyPreviewUseCase,
      useFactory: (
        installments: PrismaInstallmentRepository,
        adjustments: PrismaInstallmentAdjustmentRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
      ) =>
        new CalculatePenaltyPreviewUseCase(
          installments,
          adjustments,
          branches,
          tenantSettings,
        ),
      inject: [
        PrismaInstallmentRepository,
        PrismaInstallmentAdjustmentRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
      ],
    },
    {
      provide: ApplyPenaltyUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        installments: PrismaInstallmentRepository,
        adjustments: PrismaInstallmentAdjustmentRepository,
        operationLogs: PrismaInstallmentOperationLogRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        audit: PrismaAuditService,
      ) =>
        new ApplyPenaltyUseCase(
          unitOfWork,
          installments,
          adjustments,
          operationLogs,
          branches,
          tenantSettings,
          audit,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaInstallmentRepository,
        PrismaInstallmentAdjustmentRepository,
        PrismaInstallmentOperationLogRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PrismaAuditService,
      ],
    },
    {
      provide: ApplyDiscountUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        installments: PrismaInstallmentRepository,
        adjustments: PrismaInstallmentAdjustmentRepository,
        operationLogs: PrismaInstallmentOperationLogRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        audit: PrismaAuditService,
      ) =>
        new ApplyDiscountUseCase(
          unitOfWork,
          installments,
          adjustments,
          operationLogs,
          branches,
          tenantSettings,
          audit,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaInstallmentRepository,
        PrismaInstallmentAdjustmentRepository,
        PrismaInstallmentOperationLogRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PrismaAuditService,
      ],
    },
    {
      provide: RecordCashManualPaymentUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        installments: PrismaInstallmentRepository,
        paymentAttempts: PrismaPaymentAttemptRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        audit: PrismaAuditService,
        outbox: PrismaOutboxPublisher,
      ) =>
        new RecordCashManualPaymentUseCase(
          unitOfWork,
          installments,
          paymentAttempts,
          branches,
          tenantSettings,
          audit,
          outbox,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaInstallmentRepository,
        PrismaPaymentAttemptRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PrismaAuditService,
        PrismaOutboxPublisher,
      ],
    },
    {
      provide: RecordBankTransferPaymentUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        installments: PrismaInstallmentRepository,
        paymentAttempts: PrismaPaymentAttemptRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        audit: PrismaAuditService,
        outbox: PrismaOutboxPublisher,
      ) =>
        new RecordBankTransferPaymentUseCase(
          unitOfWork,
          installments,
          paymentAttempts,
          branches,
          tenantSettings,
          audit,
          outbox,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaInstallmentRepository,
        PrismaPaymentAttemptRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PrismaAuditService,
        PrismaOutboxPublisher,
      ],
    },
    {
      provide: RecordPosPaymentUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        installments: PrismaInstallmentRepository,
        paymentAttempts: PrismaPaymentAttemptRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        audit: PrismaAuditService,
        outbox: PrismaOutboxPublisher,
      ) =>
        new RecordPosPaymentUseCase(
          unitOfWork,
          installments,
          paymentAttempts,
          branches,
          tenantSettings,
          audit,
          outbox,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaInstallmentRepository,
        PrismaPaymentAttemptRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PrismaAuditService,
        PrismaOutboxPublisher,
      ],
    },
    {
      provide: RecordCheckPaymentUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        installments: PrismaInstallmentRepository,
        paymentAttempts: PrismaPaymentAttemptRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        audit: PrismaAuditService,
        outbox: PrismaOutboxPublisher,
      ) =>
        new RecordCheckPaymentUseCase(
          unitOfWork,
          installments,
          paymentAttempts,
          branches,
          tenantSettings,
          audit,
          outbox,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaInstallmentRepository,
        PrismaPaymentAttemptRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PrismaAuditService,
        PrismaOutboxPublisher,
      ],
    },
    {
      provide: RecordFeePaymentUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        installments: PrismaInstallmentRepository,
        paymentAttempts: PrismaPaymentAttemptRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        audit: PrismaAuditService,
        outbox: PrismaOutboxPublisher,
      ) =>
        new RecordFeePaymentUseCase(
          unitOfWork,
          installments,
          paymentAttempts,
          branches,
          tenantSettings,
          audit,
          outbox,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaInstallmentRepository,
        PrismaPaymentAttemptRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PrismaAuditService,
        PrismaOutboxPublisher,
      ],
    },
    {
      provide: ConfirmPaymentUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        installments: PrismaInstallmentRepository,
        paymentAttempts: PrismaPaymentAttemptRepository,
        branches: PrismaBranchReader,
        audit: PrismaAuditService,
        outbox: PrismaOutboxPublisher,
      ) =>
        new ConfirmPaymentUseCase(
          unitOfWork,
          installments,
          paymentAttempts,
          branches,
          audit,
          outbox,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaInstallmentRepository,
        PrismaPaymentAttemptRepository,
        PrismaBranchReader,
        PrismaAuditService,
        PrismaOutboxPublisher,
      ],
    },
    {
      provide: RejectPaymentUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        installments: PrismaInstallmentRepository,
        paymentAttempts: PrismaPaymentAttemptRepository,
        branches: PrismaBranchReader,
        audit: PrismaAuditService,
        outbox: PrismaOutboxPublisher,
      ) =>
        new RejectPaymentUseCase(
          unitOfWork,
          installments,
          paymentAttempts,
          branches,
          audit,
          outbox,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaInstallmentRepository,
        PrismaPaymentAttemptRepository,
        PrismaBranchReader,
        PrismaAuditService,
        PrismaOutboxPublisher,
      ],
    },
    {
      provide: VoidPaymentUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        installments: PrismaInstallmentRepository,
        paymentAttempts: PrismaPaymentAttemptRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        audit: PrismaAuditService,
        outbox: PrismaOutboxPublisher,
      ) =>
        new VoidPaymentUseCase(
          unitOfWork,
          installments,
          paymentAttempts,
          branches,
          tenantSettings,
          audit,
          outbox,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaInstallmentRepository,
        PrismaPaymentAttemptRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PrismaAuditService,
        PrismaOutboxPublisher,
      ],
    },
    {
      provide: GeneratePaymentReceiptUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        paymentAttempts: PrismaPaymentAttemptRepository,
        installments: PrismaInstallmentRepository,
        sales: PrismaSaleRepository,
        staff: PrismaStaffRepository,
        tenants: PrismaTenantRepository,
        branches: PrismaBranchReader,
        paymentReceipts: PrismaPaymentReceiptRepository,
        sequences: PrismaTenantSequenceRepository,
        pdfExport: IPdfExportPort,
      ) =>
        new GeneratePaymentReceiptUseCase(
          unitOfWork,
          paymentAttempts,
          installments,
          sales,
          staff,
          tenants,
          branches,
          paymentReceipts,
          sequences,
          pdfExport,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaPaymentAttemptRepository,
        PrismaInstallmentRepository,
        PrismaSaleRepository,
        PrismaStaffRepository,
        PrismaTenantRepository,
        PrismaBranchReader,
        PrismaPaymentReceiptRepository,
        PrismaTenantSequenceRepository,
        PDF_EXPORT_PORT,
      ],
    },
    {
      provide: SendPaymentReceiptUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        paymentAttempts: PrismaPaymentAttemptRepository,
        installments: PrismaInstallmentRepository,
        sales: PrismaSaleRepository,
        staff: PrismaStaffRepository,
        tenants: PrismaTenantRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        paymentReceipts: PrismaPaymentReceiptRepository,
        sequences: PrismaTenantSequenceRepository,
        notifications: PrismaNotificationDispatcher,
        audit: PrismaAuditService,
      ) =>
        new SendPaymentReceiptUseCase(
          unitOfWork,
          paymentAttempts,
          installments,
          sales,
          staff,
          tenants,
          branches,
          tenantSettings,
          paymentReceipts,
          sequences,
          notifications,
          audit,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaPaymentAttemptRepository,
        PrismaInstallmentRepository,
        PrismaSaleRepository,
        PrismaStaffRepository,
        PrismaTenantRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PrismaPaymentReceiptRepository,
        PrismaTenantSequenceRepository,
        PrismaNotificationDispatcher,
        PrismaAuditService,
      ],
    },
    {
      provide: MockPaymentGateway,
      useFactory: (config: AppConfigService) =>
        new MockPaymentGateway({
          webhookSecret: config.paymentGatewayWebhookSecret,
          publicApiBaseUrl: config.publicApiBaseUrl,
          nodeEnv: config.nodeEnv,
        }),
      inject: [AppConfigService],
    },
    {
      provide: PAYMENT_GATEWAY_REGISTRY,
      useFactory: (mockGateway: MockPaymentGateway) =>
        new MockPaymentGatewayRegistry(new Map([[mockGateway.provider, mockGateway]])),
      inject: [MockPaymentGateway],
    },
    {
      provide: InitOnlinePaymentUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        installments: PrismaInstallmentRepository,
        paymentAttempts: PrismaPaymentAttemptRepository,
        branches: PrismaBranchReader,
        tenantSettings: PrismaTenantSettingsRepository,
        gateways: IPaymentGatewayRegistry,
      ) =>
        new InitOnlinePaymentUseCase(
          unitOfWork,
          installments,
          paymentAttempts,
          branches,
          tenantSettings,
          gateways,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaInstallmentRepository,
        PrismaPaymentAttemptRepository,
        PrismaBranchReader,
        PrismaTenantSettingsRepository,
        PAYMENT_GATEWAY_REGISTRY,
      ],
    },
  ],
})
export class InstallmentsModule {}
