/** Sale / installment domain error codes — see docs/09-development/ERROR-CODES.md */
export const SaleDomainErrorCode = {
  AMOUNT_MUST_BE_POSITIVE: 'AMOUNT_MUST_BE_POSITIVE',
  AMOUNT_EXCEEDS_TOTAL: 'AMOUNT_EXCEEDS_TOTAL',
  INSTALLMENT_COUNT_INVALID: 'INSTALLMENT_COUNT_INVALID',
  DUE_DATE_IN_PAST: 'DUE_DATE_IN_PAST',
  INTERVAL_INVALID: 'INTERVAL_INVALID',
  INSTALLMENT_SUM_MISMATCH: 'INSTALLMENT_SUM_MISMATCH',
  SALE_ALREADY_CANCELLED: 'SALE_ALREADY_CANCELLED',
  SALE_ALREADY_COMPLETED: 'SALE_ALREADY_COMPLETED',
  SALE_HAS_PAID_INSTALLMENT: 'SALE_HAS_PAID_INSTALLMENT',
  INSTALLMENT_STATUS_INVALID: 'INSTALLMENT_STATUS_INVALID',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  SALE_ARCHIVED_READONLY: 'SALE_ARCHIVED_READONLY',
} as const;

export const InstallmentDomainErrorCode = {
  INSTALLMENT_ALREADY_PAID: 'INSTALLMENT_ALREADY_PAID',
  INSTALLMENT_ALREADY_WAIVED: 'INSTALLMENT_ALREADY_WAIVED',
  INSTALLMENT_STATUS_INVALID: 'INSTALLMENT_STATUS_INVALID',
  INSTALLMENT_CANNOT_DELETE: 'INSTALLMENT_CANNOT_DELETE',
  WAIVE_REASON_REQUIRED: 'WAIVE_REASON_REQUIRED',
} as const;

export const PaymentAttemptDomainErrorCode = {
  PAYMENT_ALREADY_CONFIRMED: 'PAYMENT_ALREADY_CONFIRMED',
  PAYMENT_ALREADY_REJECTED: 'PAYMENT_ALREADY_REJECTED',
  PAYMENT_ALREADY_VOIDED: 'PAYMENT_ALREADY_VOIDED',
  PAYMENT_NOT_CONFIRMED: 'PAYMENT_NOT_CONFIRMED',
  REJECT_REASON_REQUIRED: 'REJECT_REASON_REQUIRED',
  VOID_REASON_REQUIRED: 'VOID_REASON_REQUIRED',
} as const;

export type SaleDomainErrorCode =
  (typeof SaleDomainErrorCode)[keyof typeof SaleDomainErrorCode];

export type InstallmentDomainErrorCode =
  (typeof InstallmentDomainErrorCode)[keyof typeof InstallmentDomainErrorCode];

export type PaymentAttemptDomainErrorCode =
  (typeof PaymentAttemptDomainErrorCode)[keyof typeof PaymentAttemptDomainErrorCode];
