import { describe, expect, it } from 'vitest';

import { DomainError } from '../errors/domain.error.js';
import { calculateInstallmentSchedule } from './calculate-installment-schedule.js';
import { InstallmentStatus } from './installment.types.js';
import { SaleDomainErrorCode } from './errors.js';
import { Sale } from './sale.entity.js';
import {
  assertCanModifyFinancials,
  assertDownPaymentWithinTotal,
  calculateLineTotal,
  calculateSaleSubtotal,
  evaluateScheduleRegeneration,
  validateFinancialInvariant,
  validateInstallmentSum,
} from './sale-totals.calculator.js';
import { type CreateSaleInput } from './sale.types.js';

function futureUtcDate(daysFromNow = 7): Date {
  const date = new Date();
  date.setUTCDate(date.getUTCDate() + daysFromNow);
  date.setUTCHours(12, 0, 0, 0);
  return date;
}

function baseCreateInput(overrides: Partial<CreateSaleInput> = {}): CreateSaleInput {
  return {
    tenantId: '00000000-0000-0000-0000-000000000001',
    branchId: '00000000-0000-0000-0000-000000000002',
    tenantCustomerId: '00000000-0000-0000-0000-000000000003',
    createdByStaffId: '00000000-0000-0000-0000-000000000004',
    totalAmountRial: 10_000_000n,
    downPaymentRial: 0n,
    installmentCount: 3,
    firstDueDate: futureUtcDate(),
    intervalDays: 30,
    contractDate: new Date('2026-06-01'),
    ...overrides,
  };
}

describe('calculateLineTotal (IFP-070)', () => {
  it('computes quantity × unitPrice − discount + tax', () => {
    expect(
      calculateLineTotal({
        quantity: 2,
        unitPriceRial: 5_000_000n,
        discountRial: 200_000n,
        taxRial: 100_000n,
      }),
    ).toBe(9_900_000n);
  });

  it('handles single quantity without discount', () => {
    expect(
      calculateLineTotal({
        quantity: 1,
        unitPriceRial: 3_000_000n,
        discountRial: 0n,
        taxRial: 0n,
      }),
    ).toBe(3_000_000n);
  });

  it('allows zero line total when discount equals merchandise subtotal', () => {
    expect(
      calculateLineTotal({
        quantity: 1,
        unitPriceRial: 1_000_000n,
        discountRial: 1_000_000n,
        taxRial: 0n,
      }),
    ).toBe(0n);
  });

  it('rejects discount exceeding merchandise subtotal', () => {
    expect(() =>
      calculateLineTotal({
        quantity: 1,
        unitPriceRial: 1_000_000n,
        discountRial: 1_000_001n,
        taxRial: 0n,
      }),
    ).toThrow(DomainError);
  });

  it('rejects non-positive unit price', () => {
    expect(() =>
      calculateLineTotal({
        quantity: 1,
        unitPriceRial: 0n,
        discountRial: 0n,
        taxRial: 0n,
      }),
    ).toThrow(DomainError);
  });

  it('rejects invalid quantity', () => {
    expect(() =>
      calculateLineTotal({
        quantity: 0,
        unitPriceRial: 1_000_000n,
        discountRial: 0n,
        taxRial: 0n,
      }),
    ).toThrow(DomainError);
  });
});

describe('calculateSaleSubtotal (IFP-070)', () => {
  it('returns 0 for empty item list', () => {
    expect(calculateSaleSubtotal([])).toBe(0n);
  });

  it('sums multiple line totals', () => {
    const subtotal = calculateSaleSubtotal([
      {
        quantity: 1,
        unitPriceRial: 4_000_000n,
        discountRial: 0n,
        taxRial: 360_000n,
      },
      {
        quantity: 2,
        unitPriceRial: 1_000_000n,
        discountRial: 100_000n,
        taxRial: 50_000n,
      },
    ]);

    expect(subtotal).toBe(6_310_000n);
  });
});

describe('validateFinancialInvariant / validateInstallmentSum (IFP-070)', () => {
  it('passes when downPayment + installments equal total', () => {
    const result = validateFinancialInvariant({
      totalAmountRial: 10_000_000n,
      downPaymentRial: 2_000_000n,
      installmentAmounts: [3_333_334n, 3_333_333n, 1_333_333n],
    });

    expect(result.ok).toBe(true);
    expect(validateInstallmentSum({
      totalAmountRial: 10_000_000n,
      downPaymentRial: 2_000_000n,
      installmentAmounts: [3_333_334n, 3_333_333n, 1_333_333n],
    }).ok).toBe(true);
  });

  it('fails with INSTALLMENT_SUM_MISMATCH when sum differs', () => {
    const result = validateFinancialInvariant({
      totalAmountRial: 10_000_000n,
      downPaymentRial: 0n,
      installmentAmounts: [3_333_333n, 3_333_333n, 3_333_333n],
    });

    expect(result).toEqual({ ok: false, error: 'INSTALLMENT_SUM_MISMATCH' });
  });

  it('passes for full prepay with single zero installment (BR-004)', () => {
    const result = validateFinancialInvariant({
      totalAmountRial: 5_000_000n,
      downPaymentRial: 5_000_000n,
      installmentAmounts: [0n],
    });

    expect(result.ok).toBe(true);
  });

  it('matches schedule generated by calculateInstallmentSchedule (BR-005 rounding)', () => {
    const schedule = calculateInstallmentSchedule({
      totalAmountRial: 10_000_000n,
      downPaymentRial: 0n,
      installmentCount: 3,
      firstDueDate: futureUtcDate(),
      intervalDays: 30,
    });

    const result = validateFinancialInvariant({
      totalAmountRial: 10_000_000n,
      downPaymentRial: 0n,
      installmentAmounts: schedule.map((item) => item.amountRial),
    });

    expect(result.ok).toBe(true);
    expect(schedule[0].amountRial).toBe(3_333_334n);
  });
});

describe('assertDownPaymentWithinTotal (BR-002)', () => {
  it('passes when down payment equals total', () => {
    expect(() => assertDownPaymentWithinTotal(5_000_000n, 5_000_000n)).not.toThrow();
  });

  it('throws AMOUNT_EXCEEDS_TOTAL when down payment exceeds total', () => {
    expect(() => assertDownPaymentWithinTotal(5_000_000n, 5_000_001n)).toThrow(
      new DomainError(SaleDomainErrorCode.AMOUNT_EXCEEDS_TOTAL),
    );
  });
});

describe('evaluateScheduleRegeneration (IFP-070)', () => {
  it('requires regeneration when total changed and installments still match old sum', () => {
    const evaluation = evaluateScheduleRegeneration({
      previousTotalAmountRial: 10_000_000n,
      totalAmountRial: 12_000_000n,
      downPaymentRial: 0n,
      installmentAmounts: [3_333_334n, 3_333_333n, 3_333_333n],
    });

    expect(evaluation.requiresScheduleRegeneration).toBe(true);
    expect(evaluation.invariant.ok).toBe(false);
  });

  it('does not require regeneration when invariant already holds for new total', () => {
    const evaluation = evaluateScheduleRegeneration({
      previousTotalAmountRial: 10_000_000n,
      totalAmountRial: 12_000_000n,
      downPaymentRial: 0n,
      installmentAmounts: [4_000_000n, 4_000_000n, 4_000_000n],
    });

    expect(evaluation.requiresScheduleRegeneration).toBe(false);
    expect(evaluation.invariant.ok).toBe(true);
  });

  it('flags mismatch even without previous total when invariant fails', () => {
    const evaluation = evaluateScheduleRegeneration({
      totalAmountRial: 10_000_000n,
      downPaymentRial: 0n,
      installmentAmounts: [1_000_000n],
    });

    expect(evaluation.requiresScheduleRegeneration).toBe(true);
  });
});

describe('assertCanModifyFinancials (IFP-070)', () => {
  const pendingOnly = [
    {
      id: 'i-1',
      sequenceNumber: 1,
      dueDate: futureUtcDate(),
      amountRial: 5_000_000n,
      status: InstallmentStatus.PENDING,
    },
  ];

  const withPaid = [
    ...pendingOnly,
    {
      id: 'i-2',
      sequenceNumber: 2,
      dueDate: futureUtcDate(30),
      amountRial: 5_000_000n,
      status: InstallmentStatus.PAID,
    },
  ];

  it('allows active sale with no paid installments', () => {
    const { sale } = Sale.create(baseCreateInput());
    expect(() => assertCanModifyFinancials(sale, pendingOnly)).not.toThrow();
  });

  it('throws SALE_HAS_PAID_INSTALLMENT when a paid installment exists', () => {
    const { sale } = Sale.create(baseCreateInput());
    expect(() => assertCanModifyFinancials(sale, withPaid)).toThrow(
      new DomainError(SaleDomainErrorCode.SALE_HAS_PAID_INSTALLMENT),
    );
  });

  it('throws SALE_ALREADY_CANCELLED for cancelled sale', () => {
    const { sale } = Sale.create(baseCreateInput());
    sale.cancel('لغو', 'staff-1', pendingOnly);
    expect(() => assertCanModifyFinancials(sale, pendingOnly)).toThrow(
      new DomainError(SaleDomainErrorCode.SALE_ALREADY_CANCELLED),
    );
  });

  it('Sale.assertCanModifyFinancials delegates to calculator guard', () => {
    const { sale } = Sale.create(baseCreateInput());
    expect(() => sale.assertCanModifyFinancials(pendingOnly)).not.toThrow();
    expect(() => sale.assertCanModifyFinancials(withPaid)).toThrow(DomainError);
  });
});
