import {
  AUDIT_SERVICE,
  ArchiveContractUseCase,
  CancelSaleUseCase,
  ChangeSaleStatusUseCase,
  CloseContractUseCase,
  CopyContractUseCase,
  CreateContractAttachmentUseCase,
  CreateContractGuarantorUseCase,
  CreateContractCollateralUseCase,
  CreateSaleLineItemUseCase,
  BulkUpsertSaleLineItemsUseCase,
  ListSaleLineItemsUseCase,
  RecalculateSaleFinancialsUseCase,
  SoftDeleteSaleLineItemUseCase,
  UpdateSaleFinancialsUseCase,
  UpdateSaleLineItemUseCase,
  ForfeitContractCollateralUseCase,
  ListContractGuarantorsUseCase,
  ListContractCollateralsUseCase,
  ReleaseContractCollateralUseCase,
  RestoreContractGuarantorUseCase,
  SoftDeleteContractGuarantorUseCase,
  SoftDeleteContractCollateralUseCase,
  UpdateContractGuarantorUseCase,
  UpdateContractCollateralUseCase,
  CreateSaleUseCase,
  ExtendContractUseCase,
  GetContractVersionUseCase,
  GetSaleEnterpriseUseCase,
  GetSaleUseCase,
  ListContractAttachmentsUseCase,
  ListContractVersionsUseCase,
  ListSalesUseCase,
  OUTBOX_PUBLISHER,
  RestoreSaleUseCase,
  SALE_COPY_RELATED_REPOSITORY,
  SALE_IDEMPOTENCY_STORE,
  SoftDeleteContractAttachmentUseCase,
  SoftDeleteSaleUseCase,
  TerminateContractUseCase,
  UnarchiveContractUseCase,
  type AuditService,
  type IOutboxPublisher,
  type ISaleCopyRelatedRepository,
  type ISaleIdempotencyStore,
} from '@hivork/application';
import {
  MetadataSaleCopyRelatedRepository,
  NoOpInstallmentCloseWaiver,
  NoOpInstallmentScheduleExtender,
  PrismaBranchReader,
  PrismaContractAttachmentRepository,
  PrismaContractGuarantorRepository,
  PrismaContractCollateralRepository,
  PrismaContractNumberAllocator,
  PrismaContractVersionRepository,
  PrismaInstallmentRepository,
  PrismaSaleLineItemRepository,
  PrismaModule,
  PrismaOutboxPublisher,
  PrismaSaleIdempotencyStore,
  PrismaSaleRepository,
  PrismaTenantCustomerRepository,
  PrismaTenantPlanReader,
  PrismaUnitOfWork,
  RedisReportCache,
} from '@hivork/infrastructure';
import { Module } from '@nestjs/common';

import { AuthCommonModule } from '../../common/auth-common.module.js';
import { ReportsModule } from '../reports/reports.module.js';
import { SalesController } from './sales.controller.js';
import { SalesEnterpriseController } from './sales-enterprise.controller.js';
import { SaleGuarantorsController } from './sale-guarantors.controller.js';
import { SaleCollateralsController } from './sale-collaterals.controller.js';
import { SaleFinancialsController } from './sale-financials.controller.js';

@Module({
  imports: [PrismaModule, AuthCommonModule, ReportsModule],
  controllers: [
    SalesEnterpriseController,
    SaleGuarantorsController,
    SaleCollateralsController,
    SaleFinancialsController,
    SalesController,
  ],
  providers: [
    PrismaUnitOfWork,
    PrismaSaleRepository,
    PrismaInstallmentRepository,
    PrismaTenantCustomerRepository,
    PrismaBranchReader,
    PrismaTenantPlanReader,
    PrismaSaleIdempotencyStore,
    PrismaOutboxPublisher,
    PrismaContractVersionRepository,
    PrismaContractAttachmentRepository,
    PrismaContractGuarantorRepository,
    PrismaContractCollateralRepository,
    PrismaContractNumberAllocator,
    PrismaSaleLineItemRepository,
    MetadataSaleCopyRelatedRepository,
    NoOpInstallmentScheduleExtender,
    NoOpInstallmentCloseWaiver,
    {
      provide: SALE_IDEMPOTENCY_STORE,
      useExisting: PrismaSaleIdempotencyStore,
    },
    {
      provide: OUTBOX_PUBLISHER,
      useExisting: PrismaOutboxPublisher,
    },
    {
      provide: SALE_COPY_RELATED_REPOSITORY,
      useExisting: MetadataSaleCopyRelatedRepository,
    },
    {
      provide: CreateSaleUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        tenantCustomers: PrismaTenantCustomerRepository,
        branches: PrismaBranchReader,
        tenantPlans: PrismaTenantPlanReader,
        idempotency: ISaleIdempotencyStore,
        audit: AuditService,
        outbox: IOutboxPublisher,
        reportCache: RedisReportCache,
      ) =>
        new CreateSaleUseCase(
          unitOfWork,
          sales,
          installments,
          tenantCustomers,
          branches,
          tenantPlans,
          idempotency,
          audit,
          outbox,
          reportCache,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaTenantCustomerRepository,
        PrismaBranchReader,
        PrismaTenantPlanReader,
        SALE_IDEMPOTENCY_STORE,
        AUDIT_SERVICE,
        OUTBOX_PUBLISHER,
        RedisReportCache,
      ],
    },
    {
      provide: ListSalesUseCase,
      useFactory: (sales: PrismaSaleRepository) => new ListSalesUseCase(sales),
      inject: [PrismaSaleRepository],
    },
    {
      provide: GetSaleUseCase,
      useFactory: (sales: PrismaSaleRepository, installments: PrismaInstallmentRepository) =>
        new GetSaleUseCase(sales, installments),
      inject: [PrismaSaleRepository, PrismaInstallmentRepository],
    },
    {
      provide: GetSaleEnterpriseUseCase,
      useFactory: (
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        contractVersions: PrismaContractVersionRepository,
        contractAttachments: PrismaContractAttachmentRepository,
      ) =>
        new GetSaleEnterpriseUseCase(
          sales,
          installments,
          contractVersions,
          contractAttachments,
        ),
      inject: [
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaContractVersionRepository,
        PrismaContractAttachmentRepository,
      ],
    },
    {
      provide: CancelSaleUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        audit: AuditService,
        reportCache: RedisReportCache,
      ) => new CancelSaleUseCase(unitOfWork, sales, installments, audit, reportCache),
      inject: [
        PrismaUnitOfWork,
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        AUDIT_SERVICE,
        RedisReportCache,
      ],
    },
    {
      provide: ExtendContractUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        contractVersions: PrismaContractVersionRepository,
        scheduleExtender: NoOpInstallmentScheduleExtender,
        branches: PrismaBranchReader,
        audit: AuditService,
        reportCache: RedisReportCache,
      ) =>
        new ExtendContractUseCase(
          unitOfWork,
          sales,
          installments,
          contractVersions,
          scheduleExtender,
          branches,
          audit,
          reportCache,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaContractVersionRepository,
        NoOpInstallmentScheduleExtender,
        PrismaBranchReader,
        AUDIT_SERVICE,
        RedisReportCache,
      ],
    },
    {
      provide: CopyContractUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        contractVersions: PrismaContractVersionRepository,
        contractAttachments: PrismaContractAttachmentRepository,
        copyRelated: ISaleCopyRelatedRepository,
        contractNumbers: PrismaContractNumberAllocator,
        tenantCustomers: PrismaTenantCustomerRepository,
        branches: PrismaBranchReader,
        tenantPlans: PrismaTenantPlanReader,
        audit: AuditService,
        outbox: IOutboxPublisher,
        reportCache: RedisReportCache,
      ) =>
        new CopyContractUseCase(
          unitOfWork,
          sales,
          installments,
          contractVersions,
          contractAttachments,
          copyRelated,
          contractNumbers,
          tenantCustomers,
          branches,
          tenantPlans,
          audit,
          outbox,
          reportCache,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaContractVersionRepository,
        PrismaContractAttachmentRepository,
        SALE_COPY_RELATED_REPOSITORY,
        PrismaContractNumberAllocator,
        PrismaTenantCustomerRepository,
        PrismaBranchReader,
        PrismaTenantPlanReader,
        AUDIT_SERVICE,
        OUTBOX_PUBLISHER,
        RedisReportCache,
      ],
    },
    {
      provide: TerminateContractUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        contractVersions: PrismaContractVersionRepository,
        branches: PrismaBranchReader,
        audit: AuditService,
        reportCache: RedisReportCache,
      ) =>
        new TerminateContractUseCase(
          unitOfWork,
          sales,
          installments,
          contractVersions,
          branches,
          audit,
          reportCache,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaContractVersionRepository,
        PrismaBranchReader,
        AUDIT_SERVICE,
        RedisReportCache,
      ],
    },
    {
      provide: CloseContractUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        contractVersions: PrismaContractVersionRepository,
        closeWaiver: NoOpInstallmentCloseWaiver,
        branches: PrismaBranchReader,
        audit: AuditService,
        reportCache: RedisReportCache,
      ) =>
        new CloseContractUseCase(
          unitOfWork,
          sales,
          installments,
          contractVersions,
          closeWaiver,
          branches,
          audit,
          reportCache,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaContractVersionRepository,
        NoOpInstallmentCloseWaiver,
        PrismaBranchReader,
        AUDIT_SERVICE,
        RedisReportCache,
      ],
    },
    {
      provide: ArchiveContractUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        sales: PrismaSaleRepository,
        branches: PrismaBranchReader,
        audit: AuditService,
        reportCache: RedisReportCache,
      ) => new ArchiveContractUseCase(unitOfWork, sales, branches, audit, reportCache),
      inject: [PrismaUnitOfWork, PrismaSaleRepository, PrismaBranchReader, AUDIT_SERVICE, RedisReportCache],
    },
    {
      provide: UnarchiveContractUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        branches: PrismaBranchReader,
        audit: AuditService,
        reportCache: RedisReportCache,
      ) =>
        new UnarchiveContractUseCase(
          unitOfWork,
          sales,
          installments,
          branches,
          audit,
          reportCache,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaBranchReader,
        AUDIT_SERVICE,
        RedisReportCache,
      ],
    },
    {
      provide: ChangeSaleStatusUseCase,
      useFactory: (
        terminate: TerminateContractUseCase,
        close: CloseContractUseCase,
        archive: ArchiveContractUseCase,
      ) => new ChangeSaleStatusUseCase(terminate, close, archive),
      inject: [TerminateContractUseCase, CloseContractUseCase, ArchiveContractUseCase],
    },
    {
      provide: ListContractVersionsUseCase,
      useFactory: (
        sales: PrismaSaleRepository,
        contractVersions: PrismaContractVersionRepository,
      ) => new ListContractVersionsUseCase(sales, contractVersions),
      inject: [PrismaSaleRepository, PrismaContractVersionRepository],
    },
    {
      provide: GetContractVersionUseCase,
      useFactory: (
        sales: PrismaSaleRepository,
        contractVersions: PrismaContractVersionRepository,
      ) => new GetContractVersionUseCase(sales, contractVersions),
      inject: [PrismaSaleRepository, PrismaContractVersionRepository],
    },
    {
      provide: ListContractAttachmentsUseCase,
      useFactory: (
        sales: PrismaSaleRepository,
        attachments: PrismaContractAttachmentRepository,
      ) => new ListContractAttachmentsUseCase(sales, attachments),
      inject: [PrismaSaleRepository, PrismaContractAttachmentRepository],
    },
    {
      provide: CreateContractAttachmentUseCase,
      useFactory: (
        sales: PrismaSaleRepository,
        attachments: PrismaContractAttachmentRepository,
      ) => new CreateContractAttachmentUseCase(sales, attachments),
      inject: [PrismaSaleRepository, PrismaContractAttachmentRepository],
    },
    {
      provide: SoftDeleteContractAttachmentUseCase,
      useFactory: (
        sales: PrismaSaleRepository,
        attachments: PrismaContractAttachmentRepository,
      ) => new SoftDeleteContractAttachmentUseCase(sales, attachments),
      inject: [PrismaSaleRepository, PrismaContractAttachmentRepository],
    },
    {
      provide: ListContractGuarantorsUseCase,
      useFactory: (sales: PrismaSaleRepository, guarantors: PrismaContractGuarantorRepository) =>
        new ListContractGuarantorsUseCase(sales, guarantors),
      inject: [PrismaSaleRepository, PrismaContractGuarantorRepository],
    },
    {
      provide: CreateContractGuarantorUseCase,
      useFactory: (
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        guarantors: PrismaContractGuarantorRepository,
        audit: AuditService,
      ) => new CreateContractGuarantorUseCase(sales, installments, guarantors, audit),
      inject: [
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaContractGuarantorRepository,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: UpdateContractGuarantorUseCase,
      useFactory: (
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        guarantors: PrismaContractGuarantorRepository,
        audit: AuditService,
      ) => new UpdateContractGuarantorUseCase(sales, installments, guarantors, audit),
      inject: [
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaContractGuarantorRepository,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: SoftDeleteContractGuarantorUseCase,
      useFactory: (
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        guarantors: PrismaContractGuarantorRepository,
        audit: AuditService,
      ) => new SoftDeleteContractGuarantorUseCase(sales, installments, guarantors, audit),
      inject: [
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaContractGuarantorRepository,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: RestoreContractGuarantorUseCase,
      useFactory: (
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        guarantors: PrismaContractGuarantorRepository,
        audit: AuditService,
      ) => new RestoreContractGuarantorUseCase(sales, installments, guarantors, audit),
      inject: [
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaContractGuarantorRepository,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: ListContractCollateralsUseCase,
      useFactory: (sales: PrismaSaleRepository, collaterals: PrismaContractCollateralRepository) =>
        new ListContractCollateralsUseCase(sales, collaterals),
      inject: [PrismaSaleRepository, PrismaContractCollateralRepository],
    },
    {
      provide: CreateContractCollateralUseCase,
      useFactory: (
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        collaterals: PrismaContractCollateralRepository,
        audit: AuditService,
      ) => new CreateContractCollateralUseCase(sales, installments, collaterals, audit),
      inject: [
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaContractCollateralRepository,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: UpdateContractCollateralUseCase,
      useFactory: (
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        collaterals: PrismaContractCollateralRepository,
        audit: AuditService,
      ) => new UpdateContractCollateralUseCase(sales, installments, collaterals, audit),
      inject: [
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaContractCollateralRepository,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: SoftDeleteContractCollateralUseCase,
      useFactory: (
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        collaterals: PrismaContractCollateralRepository,
        audit: AuditService,
      ) => new SoftDeleteContractCollateralUseCase(sales, installments, collaterals, audit),
      inject: [
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaContractCollateralRepository,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: ReleaseContractCollateralUseCase,
      useFactory: (
        sales: PrismaSaleRepository,
        collaterals: PrismaContractCollateralRepository,
        audit: AuditService,
      ) => new ReleaseContractCollateralUseCase(sales, collaterals, audit),
      inject: [PrismaSaleRepository, PrismaContractCollateralRepository, AUDIT_SERVICE],
    },
    {
      provide: ForfeitContractCollateralUseCase,
      useFactory: (
        sales: PrismaSaleRepository,
        collaterals: PrismaContractCollateralRepository,
        audit: AuditService,
      ) => new ForfeitContractCollateralUseCase(sales, collaterals, audit),
      inject: [PrismaSaleRepository, PrismaContractCollateralRepository, AUDIT_SERVICE],
    },
    {
      provide: ListSaleLineItemsUseCase,
      useFactory: (sales: PrismaSaleRepository, lineItems: PrismaSaleLineItemRepository) =>
        new ListSaleLineItemsUseCase(sales, lineItems),
      inject: [PrismaSaleRepository, PrismaSaleLineItemRepository],
    },
    {
      provide: CreateSaleLineItemUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        lineItems: PrismaSaleLineItemRepository,
        audit: AuditService,
      ) => new CreateSaleLineItemUseCase(unitOfWork, sales, installments, lineItems, audit),
      inject: [
        PrismaUnitOfWork,
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaSaleLineItemRepository,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: BulkUpsertSaleLineItemsUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        lineItems: PrismaSaleLineItemRepository,
        audit: AuditService,
      ) => new BulkUpsertSaleLineItemsUseCase(unitOfWork, sales, installments, lineItems, audit),
      inject: [
        PrismaUnitOfWork,
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaSaleLineItemRepository,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: UpdateSaleLineItemUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        lineItems: PrismaSaleLineItemRepository,
        audit: AuditService,
      ) => new UpdateSaleLineItemUseCase(unitOfWork, sales, installments, lineItems, audit),
      inject: [
        PrismaUnitOfWork,
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaSaleLineItemRepository,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: SoftDeleteSaleLineItemUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        lineItems: PrismaSaleLineItemRepository,
        audit: AuditService,
      ) => new SoftDeleteSaleLineItemUseCase(unitOfWork, sales, installments, lineItems, audit),
      inject: [
        PrismaUnitOfWork,
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaSaleLineItemRepository,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: UpdateSaleFinancialsUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        lineItems: PrismaSaleLineItemRepository,
        audit: AuditService,
      ) => new UpdateSaleFinancialsUseCase(unitOfWork, sales, installments, lineItems, audit),
      inject: [
        PrismaUnitOfWork,
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaSaleLineItemRepository,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: RecalculateSaleFinancialsUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        lineItems: PrismaSaleLineItemRepository,
        contractVersions: PrismaContractVersionRepository,
        audit: AuditService,
      ) =>
        new RecalculateSaleFinancialsUseCase(
          unitOfWork,
          sales,
          installments,
          lineItems,
          contractVersions,
          audit,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaSaleLineItemRepository,
        PrismaContractVersionRepository,
        AUDIT_SERVICE,
      ],
    },
    {
      provide: SoftDeleteSaleUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        sales: PrismaSaleRepository,
        installments: PrismaInstallmentRepository,
        branches: PrismaBranchReader,
        audit: AuditService,
        reportCache: RedisReportCache,
      ) =>
        new SoftDeleteSaleUseCase(
          unitOfWork,
          sales,
          installments,
          branches,
          audit,
          reportCache,
        ),
      inject: [
        PrismaUnitOfWork,
        PrismaSaleRepository,
        PrismaInstallmentRepository,
        PrismaBranchReader,
        AUDIT_SERVICE,
        RedisReportCache,
      ],
    },
    {
      provide: RestoreSaleUseCase,
      useFactory: (
        unitOfWork: PrismaUnitOfWork,
        sales: PrismaSaleRepository,
        audit: AuditService,
        reportCache: RedisReportCache,
      ) => new RestoreSaleUseCase(unitOfWork, sales, audit, reportCache),
      inject: [PrismaUnitOfWork, PrismaSaleRepository, AUDIT_SERVICE, RedisReportCache],
    },
  ],
})
export class SalesModule {}
