import { z } from 'zod';

export const ErrorCodes = {
  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  VERIFIED_TOKEN_EXPIRED: 'VERIFIED_TOKEN_EXPIRED',
  VERIFIED_TOKEN_INVALID: 'VERIFIED_TOKEN_INVALID',
  AUTH_PASSWORD_TOO_WEAK: 'AUTH_PASSWORD_TOO_WEAK',
  AUTH_CREDENTIAL_ALREADY_EXISTS: 'AUTH_CREDENTIAL_ALREADY_EXISTS',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_MUST_CHANGE_PASSWORD: 'AUTH_MUST_CHANGE_PASSWORD',
  AUTH_CAPTCHA_INVALID: 'AUTH_CAPTCHA_INVALID',
  AUTH_CAPTCHA_REQUIRED: 'AUTH_CAPTCHA_REQUIRED',
  CAPTCHA_SERVICE_UNAVAILABLE: 'CAPTCHA_SERVICE_UNAVAILABLE',
  AUTH_IP_NOT_ALLOWED: 'AUTH_IP_NOT_ALLOWED',
  AUTH_LOGIN_RATE_LIMITED: 'AUTH_LOGIN_RATE_LIMITED',
  AUTH_MFA_TOKEN_INVALID: 'AUTH_MFA_TOKEN_INVALID',
  AUTH_MFA_TOKEN_EXPIRED: 'AUTH_MFA_TOKEN_EXPIRED',
  AUTH_MFA_NOT_ENABLED: 'AUTH_MFA_NOT_ENABLED',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_TOO_MANY_ATTEMPTS: 'AUTH_OTP_TOO_MANY_ATTEMPTS',
  AUTH_OTP_RATE_LIMITED: 'AUTH_OTP_RATE_LIMITED',
  AUTH_TOTP_INVALID: 'AUTH_TOTP_INVALID',
  AUTH_RESET_TOKEN_EXPIRED: 'AUTH_RESET_TOKEN_EXPIRED',
  AUTH_RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',
  AUTH_PASSWORD_REUSED: 'AUTH_PASSWORD_REUSED',
  AUTH_API_KEY_INVALID: 'AUTH_API_KEY_INVALID',
  AUTH_API_KEY_REVOKED: 'AUTH_API_KEY_REVOKED',
  AUTH_API_KEY_EXPIRED: 'AUTH_API_KEY_EXPIRED',
  AUTH_API_KEY_RATE_LIMITED: 'AUTH_API_KEY_RATE_LIMITED',
  API_KEY_NAME_EXISTS: 'API_KEY_NAME_EXISTS',
  API_KEY_NOT_FOUND: 'API_KEY_NOT_FOUND',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  AUTH_PHONE_CHANGE_EXPIRED: 'AUTH_PHONE_CHANGE_EXPIRED',
  AUTH_PHONE_CHANGE_IN_PROGRESS: 'AUTH_PHONE_CHANGE_IN_PROGRESS',
  PHONE_ALREADY_IN_USE: 'PHONE_ALREADY_IN_USE',
  INVALID_PHONE: 'INVALID_PHONE',
  STAFF_SUSPENDED: 'STAFF_SUSPENDED',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  AUTH_REFRESH_EXPIRED: 'AUTH_REFRESH_EXPIRED',
  AUTH_REFRESH_COMPROMISED: 'AUTH_REFRESH_COMPROMISED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_ALREADY_REVOKED: 'SESSION_ALREADY_REVOKED',
  INVALID_CURSOR: 'INVALID_CURSOR',

  // Resource
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  ALREADY_EXISTS: 'ALREADY_EXISTS',

  // Soft delete (ADR-013)
  HARD_DELETE_FORBIDDEN: 'HARD_DELETE_FORBIDDEN',
  ALREADY_DELETED: 'ALREADY_DELETED',
  NOT_DELETED: 'NOT_DELETED',
  DELETE_FORBIDDEN: 'DELETE_FORBIDDEN',
  RESTORE_FORBIDDEN: 'RESTORE_FORBIDDEN',

  // Domain / plan
  DOMAIN_ERROR: 'DOMAIN_ERROR',
  MODULE_NOT_ENABLED: 'MODULE_NOT_ENABLED',
  PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',
  CANNOT_DEACTIVATE_DEFAULT_BRANCH: 'CANNOT_DEACTIVATE_DEFAULT_BRANCH',

  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export const ApiErrorSchema = z.object({
  code: z.string(),
  message: z.string(),
  details: z.record(z.unknown()).optional(),
});

export type ApiError = z.infer<typeof ApiErrorSchema>;

export function parseApiError(body: unknown): ApiError | null {
  const parsed = ApiErrorSchema.safeParse(body);
  return parsed.success ? parsed.data : null;
}
